Repository openshift-kni/numaresources-operator, pull requests merged in 2022-09, with the labels that each got.

#401 RTE: enable refresh-node-resources feature
  go.mod
  go.sum
  hack/run-test-e2e.sh
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/rte/rte_test.go
  rte/main.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/clusterrole.yaml
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/prometheus/prometheus.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/conditions.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/topology_updater/topology_updater.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodetopology/nodetopology.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/pods/pods.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go
  vendor/modules.txt
Labels: approved, lgtm

#402 deps: trivial bump
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/manifests.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/modules.txt
Labels: approved, lgtm

#398 e2e: serial lane cleanup and fixes
  rte/main.go
  rte/pkg/sysinfo/sysinfo.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, do-not-merge/hold

#410 e2e: serial: enhance and use the pause image
  Dockerfile.pause
  Makefile
  README.tests.md
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/images/consts.go
  test/utils/objects/consts.go
Labels: approved, lgtm

#411 e2e: fixture: serial: configurable cooldown
  test/e2e/serial/README.md
  test/utils/fixture/fixture.go
Labels: approved

#415 e2e:serial:tmpolicy: introduce tmPolicyFuncs
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
Labels: approved, lgtm

#416 e2e:serial:tmpolicy: test device NUMA alignment
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#417 serial: set container images via the function
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/images/consts.go
  test/utils/objects/consts.go
  test/utils/objects/pod.go
Labels: approved, lgtm

#420 e2e: serial: negative-test: topology alignment of pod requesting devices
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#421 e2e: serial: fixture: configurable teardown time
  test/e2e/serial/README.md
  test/utils/fixture/fixture.go
Labels: approved, lgtm

#419 serial: add tests with device resources
  test/e2e/serial/README.md
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/fixture/devices.go
Labels: approved, lgtm

#424 e2e: serial: add label to group nonregression test
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/non_regression_fundamentals.go
Labels: approved

#425 miscelaneous fixes 20220927
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/numaresourcesoperator_controller.go
  pkg/objectstate/rte/rte.go
Labels: approved

#426 deps: bump RTE to v0.7.3, PFP to v0.0.3
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/modules.txt
Labels: approved

#427 kustomize: allow the workload type management in ns
  config/manager/manager.yaml
Labels: approved, lgtm

#423 serial: device resources cleanup
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#429 adjust the copyright to Red Hat
  internal/nodes/nodes.go
  test/e2e/install/install_test.go
  test/e2e/install/test_suite_install_test.go
  test/e2e/rte/rte_e2e_suite_test.go
  test/e2e/rte/rte_test.go
  test/e2e/sched/install/install_test.go
  test/e2e/sched/install/test_suite_install_test.go
  test/e2e/sched/sched_test.go
  test/e2e/sched/test_suite_sched_test.go
  test/e2e/sched/uninstall/test_suite_uninstall_test.go
  test/e2e/sched/uninstall/uninstall_test.go
  test/e2e/sched/utils/daemonset.go
  test/e2e/sched/utils/deployment.go
  test/e2e/sched/utils/node.go
  test/e2e/sched/utils/replicaset.go
  test/e2e/serial/e2e_serial_test.go
  test/e2e/uninstall/test_suite_uninstall_test.go
  test/e2e/uninstall/uninstall_test.go
  test/utils/clients/clients.go
  test/utils/configuration/configuration.go
  test/utils/crds/crds.go
  test/utils/fixture/fixture.go
  test/utils/images/consts.go
  test/utils/images/images.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  test/utils/nrosched/nrosched.go
  test/utils/objects/replicaset.go
  test/utils/padder/padder.go
  test/utils/runtime/runtime.go
  tools/tools.go
Labels: approved, lgtm
