Repository openshift-kni/numaresources-operator, pull requests merged in 2022-06, with the labels that each got.

#293 scheduler: force order of filters
  pkg/numaresourcesscheduler/manifests/yaml/configmap.nrt.yaml
Labels: approved, lgtm

#301 deps: bump deployer to v0.6.1
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/rte/rte-notifier.sh
  vendor/modules.txt
Labels: approved, lgtm

#302 build: introduce buildhelper replacing git-semver
  Makefile
  hack/buildhelper/buildhelper.go
  hack/tools.go
  main.go
  pkg/version/version.go
  pkg/version/version_test.go
  rte/main.go
Labels: approved, lgtm

#303 [release-4.10][manual] fix versioning 4.10
  Makefile
  hack/buildhelper/buildhelper.go
  hack/tools.go
  main.go
  pkg/version/version.go
  pkg/version/version_test.go
  rte/main.go
Labels: approved, lgtm

#307 olm:csv: add skipRange annotation
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#306 miscelanous code cleanup - 20220615
  Makefile
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesscheduler_controller.go
  main.go
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
  pkg/numaresourcesscheduler/objectstate/sched/sched_test.go
  pkg/objectstate/rte/rte.go
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/sched/sched.go
  pkg/objectupdate/sched/sched_test.go
  rte/main.go
  rte/pkg/config/watcher.go
  rte/pkg/config/watcher_test.go
  test/e2e/rte/rte_test.go
Labels: approved, lgtm

#308 e2e:serial: scope=container tests enablement
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
Labels: approved, lgtm, cherry-pick-candidate

#310 e2e: serial tests fixes and tuning
  internal/noderesourcetopology/tostring.go
  internal/noderesourcetopology/tostring_test.go
  internal/resourcelist/resourcelist.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  test/utils/objects/wait/deployment.go
Labels: approved, cherry-pick-candidate
