Repository openshift-kni/numaresources-operator, pull requests merged in 2022-03, with the labels that each got.

#152 Create validation logic to check cluster
  Makefile
  controllers/kubeletconfig_controller.go
  controllers/kubeletconfig_controller_test.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  go.mod
  go.sum
  nrocli/main.go
  pkg/kubeletconfig/kubeletconfig.go
  pkg/machineconfigpools/find/machineconfigpools.go
  pkg/machineconfigpools/machineconfigpools.go
  pkg/objectnames/objectnames.go
  pkg/validator/kubeletconfigvalidator.go
  test/e2e/rte/rte_test.go
  vendor/github.com/aquasecurity/go-version/LICENSE
  vendor/github.com/aquasecurity/go-version/pkg/part/any.go
  vendor/github.com/aquasecurity/go-version/pkg/part/empty.go
  vendor/github.com/aquasecurity/go-version/pkg/part/infinity.go
  vendor/github.com/aquasecurity/go-version/pkg/part/int.go
  vendor/github.com/aquasecurity/go-version/pkg/part/list.go
  vendor/github.com/aquasecurity/go-version/pkg/part/part.go
  vendor/github.com/aquasecurity/go-version/pkg/part/string.go
  vendor/github.com/aquasecurity/go-version/pkg/prerelease/prerelease.go
  vendor/github.com/aquasecurity/go-version/pkg/version/constraint.go
  vendor/github.com/aquasecurity/go-version/pkg/version/version.go
  vendor/github.com/aquasecurity/go-version/pkg/version/version_collection.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/clientutil/client.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/kubeletconfig/configz.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/kubeletconfig/kubectl.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/validator/clusterversion.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/validator/kubeletconfig.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/validator/validator.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#187 rte: don't use google pause container
  controllers/numaresourcesoperator_controller.go
  main.go
  pkg/objectstate/rte/rte.go
Labels: approved, lgtm

#189 deps: rte: consume latest changes from u/s
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go
  vendor/modules.txt
Labels: approved, lgtm

#194 e2e: make it easier to integrate the NROP testsuite
  Dockerfile.openshift.tests
  Dockerfile.tests
  Makefile
  hack/render-e2e-runner.sh
  hack/run-test-e2e.sh
  hack/run-test-install-e2e.sh
  hack/run-test-serial-e2e.sh
  test/e2e/serial/test_suite_serial_test.go
Labels: approved, lgtm

#199 hack: dockerfile: add pause entrypoint
  Dockerfile.openshift.tests
  Dockerfile.tests
  Makefile
  README.md
  hack/pause
Labels: approved, lgtm

#197 e2e node selector and resources in one NUMA zone
  test/e2e/serial/workload_placement_test.go
Labels: approved, lgtm, cherry-pick-candidate

#201 [release-4.10][manual] hack: dockerfile: add pause entrypoint
  Dockerfile.openshift.tests
  Dockerfile.tests
  Makefile
  hack/pause
Labels: approved, lgtm

#188 ConfigMap hash annotation in workload resources
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/hash/configmap.go
  pkg/hash/configmap_test.go
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
  pkg/numaresourcesscheduler/objectstate/sched/sched_test.go
  pkg/objectstate/rte/rte.go
  vendor/github.com/asaskevich/govalidator/.travis.yml
  vendor/github.com/asaskevich/govalidator/CONTRIBUTING.md
  vendor/github.com/asaskevich/govalidator/LICENSE
  vendor/github.com/asaskevich/govalidator/README.md
  vendor/github.com/asaskevich/govalidator/arrays.go
  vendor/github.com/asaskevich/govalidator/converter.go
  vendor/github.com/asaskevich/govalidator/error.go
  vendor/github.com/asaskevich/govalidator/numerics.go
  vendor/github.com/asaskevich/govalidator/patterns.go
  vendor/github.com/asaskevich/govalidator/types.go
  vendor/github.com/asaskevich/govalidator/utils.go
  vendor/github.com/asaskevich/govalidator/validator.go
  vendor/github.com/asaskevich/govalidator/wercker.yml
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#202 e2e:serial: use a lowercase letters in pod name
  test/e2e/serial/workload_placement_test.go
Labels: approved, lgtm, cherry-pick-candidate

#163 e2e-workload: Workload requests guaranteed pod resources available on one node but not on a single numa
  test/e2e/sched/utils/daemonset.go
  test/e2e/serial/workload_placement_test.go
  test/utils/objects/daemonset.go
Labels: approved, lgtm, cherry-pick-candidate

#203 e2e:serial: schedule guaranteed pod in selective way
  test/e2e/serial/workload_placement_test.go
Labels: approved, lgtm, cherry-pick-candidate

#190 e2e Check pod overhead is not accounted on NRT.
  test/e2e/serial/workload_placement_test.go
Labels: approved, lgtm, cherry-pick-candidate

#172 e2e test: Burstable pod not fitting any NUMA zone
  test/e2e/serial/workload_placement_test.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  test/utils/padder/padder.go
Labels: approved, lgtm, cherry-pick-candidate

#207 [release-4.10][manual] ConfigMap hash annotation in workload resources
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/hash/configmap.go
  pkg/hash/configmap_test.go
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
  pkg/numaresourcesscheduler/objectstate/sched/sched_test.go
  pkg/objectstate/rte/rte.go
  vendor/github.com/asaskevich/govalidator/.travis.yml
  vendor/github.com/asaskevich/govalidator/CONTRIBUTING.md
  vendor/github.com/asaskevich/govalidator/LICENSE
  vendor/github.com/asaskevich/govalidator/README.md
  vendor/github.com/asaskevich/govalidator/arrays.go
  vendor/github.com/asaskevich/govalidator/converter.go
  vendor/github.com/asaskevich/govalidator/error.go
  vendor/github.com/asaskevich/govalidator/numerics.go
  vendor/github.com/asaskevich/govalidator/patterns.go
  vendor/github.com/asaskevich/govalidator/types.go
  vendor/github.com/asaskevich/govalidator/utils.go
  vendor/github.com/asaskevich/govalidator/validator.go
  vendor/github.com/asaskevich/govalidator/wercker.yml
  vendor/modules.txt
Labels: approved, lgtm

#185 e2e: serial: Modify configurable values
  test/e2e/serial/test_suite_serial_test.go
  test/e2e/serial/workload_placement_test.go
  test/utils/nodes/nodes.go
  test/utils/objects/wait/machineconfig.go
Labels: approved, lgtm, cherry-pick-candidate

#205 e2e: serial: start the non-regression and unschedulable test groups
  test/e2e/serial/non_regression_test.go
  test/e2e/serial/workload_placement_test.go
  test/e2e/serial/workload_unschedulable_test.go
  test/utils/nrosched/nrosched.go
Labels: approved, lgtm, cherry-pick-candidate

#210 e2e: add [tierX] labels
  test/e2e/install/install_test.go
  test/e2e/sched/install/install_test.go
  test/e2e/serial/non_regression_test.go
  test/e2e/serial/sched_removal_test.go
  test/e2e/serial/workload_placement_test.go
  test/e2e/serial/workload_unschedulable_test.go
Labels: approved, lgtm

#208 e2e: serial: split more tests form `workload_placement_test.go`
  test/e2e/serial/workload_overhead_test.go
  test/e2e/serial/workload_placement_test.go
  test/e2e/serial/workload_unschedulable_test.go
Labels: approved, lgtm, cherry-pick-candidate

#171 e2e: serial: generalize test multi-container placement
  test/e2e/serial/workload_placement_test.go
  test/e2e/serial/workload_placement_tmpol_test.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/modules.txt
Labels: approved, cherry-pick-candidate

#211 e2e: serial: split tests form `workload_placement_test.go` - take 2
  test/e2e/serial/configuration_test.go
  test/e2e/serial/resource_accounting_test.go
  test/e2e/serial/workload_overhead_test.go
  test/e2e/serial/workload_placement_nodesel_test.go
  test/e2e/serial/workload_placement_test.go
  test/e2e/serial/workload_placement_tmpol_test.go
Labels: approved, lgtm, cherry-pick-candidate

#212 e2e: serial: split tests form `workload_placement_test.go` - take 3
  hack/run-test-serial-e2e.sh
  test/e2e/install/install_test.go
  test/e2e/sched/install/install_test.go
  test/e2e/serial/workload_placement_taint_test.go
  test/e2e/serial/workload_placement_test.go
Labels: approved, lgtm, cherry-pick-candidate

#213 e2e: serial: split tests form workload_placement_test.go - take 4
  test/e2e/serial/resource_accounting_test.go
  test/e2e/serial/workload_placement_test.go
Labels: approved, lgtm

#215 e2e: add test_id to It blocks
  test/e2e/serial/sched_removal_test.go
Labels: approved, lgtm

#218 Ci fixes 20220314
  .github/workflows/e2e.yml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml
  doc/examples/sched.yaml
  hack/run-test-e2e.sh
  rte/hack/run-e2e-kni.sh
  test/utils/objects/objects.go
Labels: approved, lgtm

#216 e2e: serial: make it easier to integrate
  test/e2e/serial/README.md
  test/e2e/serial/e2e_serial_test.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/e2e_suite.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodesel.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/configuration/configuration.go
Labels: approved, lgtm

#219 e2e: serial: move away Before/AfterSuite
  test/e2e/serial/e2e_serial_test.go
  test/e2e/serial/tests/e2e_suite.go
Labels: approved, lgtm

#222 e2e: skip with call stack offset
  test/e2e/serial/tests/workload_placement.go
Labels: approved, lgtm

#221 fix and unconditionally enable the workload placement by tm scope tests
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/nodes/baseload.go
Labels: approved, lgtm, cherry-pick-candidate

#223 e2e: numacell: move logic in packages
  test/deviceplugin/cmd/numacell/main.go
  test/deviceplugin/pkg/numacell/cmd/numacell.go
Labels: approved, lgtm

#225 Dockerfile: fix envsubst dependency
  Makefile
  go.mod
  go.sum
  hack/envsubst.go
  hack/render-e2e-runner.sh
  hack/run-test-serial-e2e.sh
  test/e2e/serial/e2e_serial_test.go
  vendor/github.com/drone/envsubst/.drone.yml
  vendor/github.com/drone/envsubst/.gitignore
  vendor/github.com/drone/envsubst/LICENSE
  vendor/github.com/drone/envsubst/eval.go
  vendor/github.com/drone/envsubst/funcs.go
  vendor/github.com/drone/envsubst/parse/node.go
  vendor/github.com/drone/envsubst/parse/parse.go
  vendor/github.com/drone/envsubst/parse/scan.go
  vendor/github.com/drone/envsubst/path/match.go
  vendor/github.com/drone/envsubst/readme.md
  vendor/github.com/drone/envsubst/template.go
  vendor/modules.txt
Labels: approved, lgtm

#228 e2e: add serial config suite
  test/e2e/serial/config/config.go
  test/e2e/serial/config/fixture.go
  test/e2e/serial/config/infra.go
  test/e2e/serial/e2e_serial_test.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodesel.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/fixture/fixture.go
  test/utils/padder/padder.go
Labels: approved

#232 [release-4.10][manual] Update pcidb to 1.0.0
  Dockerfile
  Dockerfile.openshift
  Dockerfile.openshift.rte
  go.mod
  go.sum
  vendor/github.com/jaypipes/pcidb/.get-go-packages.sh
  vendor/github.com/jaypipes/pcidb/.travis.yml
  vendor/github.com/jaypipes/pcidb/Gopkg.lock
  vendor/github.com/jaypipes/pcidb/Gopkg.toml
  vendor/github.com/jaypipes/pcidb/Makefile
  vendor/github.com/jaypipes/pcidb/README.md
  vendor/github.com/jaypipes/pcidb/context.go
  vendor/github.com/jaypipes/pcidb/discover.go
  vendor/github.com/jaypipes/pcidb/main.go
  vendor/modules.txt
Labels: approved, lgtm

#235 utils: baseload: fix GetLoad() to correctly reflect the node load
  test/utils/nodes/baseload.go
Labels: approved, lgtm

#237 project: add the internal/ hierarchy
  Makefile
  hack/tools.go
  internal/baseload/baseload.go
  internal/baseload/baseload_test.go
  internal/resourcelist/resourcelist.go
  internal/resourcelist/resourcelist_test.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  test/utils/nodes/nodes.go
Labels: approved, lgtm

#230 e2e:serial: modify kubeletconfig while TAS is running
  pkg/kubeletconfig/kubeletconfig.go
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#238 e2e: serial: fix rebase glitch
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#239 e2e: serial: generalize tmscope-agnostic tests
  test/e2e/sched/utils/deployment.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/fixture/fixture.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
Labels: approved, lgtm
