Repository openshift-kni/numaresources-operator, pull requests merged in 2022-07, with the labels that each got.

#312 testing: improve unit tests coverage
  internal/objects/objects_test.go
  pkg/objectnames/objectnames_test.go
Labels: approved, lgtm

#313 static-pods: Document the behaviour of static pods
  README.md
Labels: approved, lgtm

#305 RTE: update to consume pods fingerprinting support
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  controllers/numaresourcesoperator_controller.go
  go.mod
  go.sum
  pkg/machineconfigpools/machineconfigpools.go
  pkg/machineconfigpools/machineconfigpools_test.go
  pkg/objectstate/rte/rte.go
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/rte/rte_test.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
  rte/main.go
  test/e2e/rte/rte_test.go
  vendor/github.com/OneOfOne/xxhash/.gitignore
  vendor/github.com/OneOfOne/xxhash/.travis.yml
  vendor/github.com/OneOfOne/xxhash/LICENSE
  vendor/github.com/OneOfOne/xxhash/README.md
  vendor/github.com/OneOfOne/xxhash/xxhash.go
  vendor/github.com/OneOfOne/xxhash/xxhash_go17.go
  vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
  vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/LICENSE
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/README.md
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/k8sannotations/annotations.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/notification/notification.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourceobserver.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodetopology/nodetopology.go
  vendor/github.com/mdomke/git-semver/.gitignore
  vendor/github.com/mdomke/git-semver/README.md
  vendor/github.com/mdomke/git-semver/main.go
  vendor/modules.txt
Labels: approved, lgtm

#319 e2e:serial: check scheduling error per topology scope
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/nrosched/nrosched.go
Labels: approved, lgtm, test-case-followup

#321 e2e: serial: tests for non-guaranteed pods
  test/e2e/serial/tests/resource_accounting.go
Labels: approved, lgtm

#328 api: bundle: add OLM spec desc refs for logLevel
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#336 Dockerfile: fully qualified builder images
  Dockerfile
  Dockerfile.tests
Labels: approved, lgtm

#342 e2e:serial: remove requirement for scope=pod in unsched tests
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, cherry-pick-candidate

#325 e2e:serial: deflake podscope failures
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm, cherry-pick-candidate

#346 e2e: install: minimal fixes
  controllers/numaresourcesoperator_controller.go
  test/e2e/install/install_test.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/workload_placement.go
  test/utils/objects/daemonset.go
  test/utils/objects/objects.go
  test/utils/objects/pod.go
  test/utils/objects/wait/daemonset.go
Labels: approved, lgtm, cherry-pick-candidate

#343 tools: move from `hack` in a proper directory
  Makefile
  hack/run-test-tools-e2e.sh
  test/e2e/tools/test_suite_tools_test.go
  test/e2e/tools/tools_test.go
  test/utils/runtime/runtime.go
  tools/buildhelper/buildhelper.go
  tools/envsubst/envsubst.go
  tools/lsplatform/lsplatform.go
  tools/tools.go
Labels: approved, lgtm, cherry-pick-candidate

#324 e2e fixes and cleanups
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  main.go
  test/e2e/install/install_test.go
  test/e2e/rte/rte_test.go
  test/e2e/sched/install/install_test.go
  test/e2e/sched/sched_test.go
  test/e2e/sched/uninstall/uninstall_test.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/e2e/uninstall/uninstall_test.go
  test/utils/fixture/fixture.go
Labels: approved, lgtm, cherry-pick-candidate

#355 e2e: serial: default scheduler: deployment with gu pod on a node
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/nrosched/nrosched.go
Labels: approved, lgtm

#351 e2e: serial: schedule gu pod as part of a deployment to a specific node
  test/e2e/serial/tests/non_regression.go
Labels: approved, lgtm

#359 numaresourcesscheduler: fix service-account's merge function
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
Labels: approved, lgtm, cherry-pick-candidate

#354 e2e: serial: daemonset with non-gu pod requesting resources on a node
  test/e2e/serial/tests/resource_accounting.go
Labels: approved, lgtm

#357 e2e:serial: schedule Burstable pod and verifies no NRT changes
  test/e2e/serial/tests/resource_accounting.go
Labels: approved, lgtm

#364 e2e: change image for init containers
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#339 Must gather e2e test
  hack/run-test-must-gather-e2e.sh
  test/e2e/install/install_test.go
  test/e2e/must-gather/must_gather_suite_test.go
  test/e2e/must-gather/must_gather_test.go
  test/utils/deploy/deploy.go
  test/utils/objects/wait/numaresources.go
Labels: approved, lgtm

#352 e2e:serial:cntscope:negative filter node based on single resource shortage
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#367 docs: limitations: we now support scope=container
  README.md
Labels: approved, lgtm

#372 e2e: fix resource accounting tests
  test/e2e/serial/tests/resource_accounting.go
Labels: approved, lgtm, cherry-pick-candidate, followup-needed

#370 e2e: serial: Resources shared by burstable and guaranteed pods
  test/e2e/serial/tests/resource_accounting.go
Labels: approved, lgtm, followup-needed
