Repository openshift-kni/numaresources-operator, pull requests merged in 2022-10, with the labels that each got.

#428 serial: add negative test with pod scope and devices
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#430 validator: check pod phase on relevant pods
  pkg/validation/validation.go
  pkg/validation/validation_suite_test.go
  pkg/validation/validation_test.go
  pkg/validator/podstatus.go
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: approved

#431 RTE: enable per-node-group tuning
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_defaults.go
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  go.mod
  go.sum
  internal/objects/objects.go
  pkg/flagcodec/flagcodec.go
  pkg/flagcodec/flagcodec_test.go
  pkg/objectstate/merge/merge.go
  pkg/objectstate/merge/merge_test.go
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/rte/rte_test.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/codec.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/manifests.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/modules.txt
Labels: approved, lgtm

#433 serial: add the new variable E2E_RTE_CI_IMAGE
  test/e2e/serial/README.md
  test/e2e/serial/config/config.go
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#434 e2e: serial: avoid cooldown on test skip
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/non_regression_fundamentals.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/fixture/fixture.go
Labels: approved

#437 Cleanup 20221012
  internal/nodes/nodes.go
  internal/podlist/daemonset.go
  internal/podlist/deployment.go
  internal/podlist/replicaset.go
  pkg/objectnames/objectnames.go
  test/e2e/sched/install/install_test.go
  test/e2e/sched/sched_test.go
  test/e2e/sched/uninstall/uninstall_test.go
  test/e2e/sched/utils/node.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/clients/clients.go
  test/utils/objects/objects.go
Labels: approved

#438 e2e: fixture: add pod-security label
  test/utils/fixture/fixture.go
Labels: approved, lgtm

#439 Cleanup 20221013
  hack/run-test-serial-e2e.sh
  test/e2e/serial/tests/sched_removal.go
Labels: approved

#440 test: deps: consume dpm 1.19.3
  go.mod
  go.sum
  vendor/github.com/kubevirt/device-plugin-manager/pkg/dpm/plugin.go
  vendor/modules.txt
Labels: approved, lgtm

#435 serial: enhance test verbosity and reduce execution time
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#441 rte: sched: manifest: enable sched plugin tracing
  go.mod
  go.sum
  pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
  pkg/objectupdate/rte/rte.go
  rte/main.go
  test/e2e/rte/rte_test.go
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/README.md
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/modules.txt
Labels: approved

#447 [release-4.11][manual] partial backport of PR #324
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  main.go
Labels: approved, cherry-pick-candidate

#449 numacell: more kubernetes 1.25 compatibility
  go.mod
  go.sum
  test/deviceplugin/pkg/numacell/plugin/numacell.go
  vendor/github.com/kubevirt/device-plugin-manager/pkg/dpm/plugin.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#450 rte: config: fix setting of TM scope
  rte/main.go
  test/e2e/rte/rte_e2e_suite_test.go
  test/e2e/rte/rte_local_test.go
Labels: approved, lgtm, cherry-pick-candidate

#451 test: e2e: rte: fix configuration test
  test/e2e/rte/rte_e2e_suite_test.go
  test/e2e/rte/rte_local_test.go
  test/utils/runtime/runtime.go
Labels: approved

#452 e2e: fix unsuitable free devices amount
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#453 test: e2e: rte: move to dedicated GH actions lane
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yml
  .github/workflows/e2e.yml
  hack/run-test-e2e.sh
  test/utils/runtime/runtime.go
Labels: approved, lgtm, cherry-pick-candidate

#457 rte: add exclude list for pod namespaces/name
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/kubeletconfig_controller.go
  rte/main.go
  rte/pkg/config/config.go
  rte/pkg/podresfilter/client.go
Labels: approved, lgtm

#458 rte: cleanup code
  rte/pkg/config/config.go
  rte/pkg/config/config_test.go
  rte/pkg/podrescompat/client.go
  rte/pkg/podrescompat/client_test.go
  rte/pkg/podresfilter/client.go
  rte/pkg/podresfilter/client_test.go
  rte/pkg/sysinfo/sysinfo.go
  rte/pkg/sysinfo/sysinfo_test.go
Labels: approved, cherry-pick-candidate

#456 RTE: proper node group status reporting
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller.go
Labels: approved, cherry-pick-candidate

#459 serial: update scheduler name properly
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#455 serial: add new tests with device resources
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#461 serial: add new tests with device resources
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/qos/qos.go
  vendor/modules.txt
Labels: approved, lgtm
