Repository openshift-kni/numaresources-operator, pull requests merged in 2022-11, with the labels that each got.

#462 serial: support test for pod TMscope
  test/e2e/serial/tests/workload_placement.go
Labels: approved, lgtm

#460 RTE: further improvements about node group config status reporting
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  pkg/machineconfigpools/machineconfigpools.go
  pkg/normalize/normalize.go
  pkg/normalize/normalize_test.go
  test/e2e/serial/tests/configuration.go
Labels: approved, cherry-pick-candidate

#463 serial: fix failing test
  internal/wait/replicaset.go
  test/e2e/serial/tests/workload_placement.go
Labels: approved, lgtm

#464 internal: unexport and rename internal helper functions
  internal/wait/deployment.go
  internal/wait/replicaset.go
  test/e2e/serial/tests/workload_placement.go
Labels: approved, lgtm

#467 Cleanup 20221107
  test/e2e/serial/README.md
  test/utils/fixture/devices.go
Labels: approved, lgtm

#468 serial: pass pod's address properly to the function
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm

#469 Cleanup 20221109
  test/e2e/sched/install/install_test.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm

#472 hack: add ginkgo v2 timeout for serial
  hack/run-test-e2e.sh
  hack/run-test-install-e2e.sh
  hack/run-test-must-gather-e2e.sh
  hack/run-test-serial-e2e.sh
  hack/run-test-tools-e2e.sh
  hack/test-e2e-runner.sh
Labels: approved, lgtm

#473 Cleanup 20221111
  controllers/controllers_suite_test.go
  controllers/kubeletconfig_controller.go
  controllers/kubeletconfig_controller_test.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  test/e2e/sched/install/install_test.go
  test/e2e/serial/config/fixture.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/nrosched/nrosched.go
  test/utils/objects/objects.go
Labels: approved

#474 e2e: serial: handle missing NodeGroupConfig in spec
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#471 serial tests fixes
  internal/wait/daemonset.go
  internal/wait/deployment.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm

#475 prepare the switch to golang 1.19 toolchain
  Dockerfile.tools
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/ratelimiter/ratelimiter.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/test/e2e/framework/nodes_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved

#476 build: move to golang 1.19
  .github/workflows/cibuild.yml
  .github/workflows/ciformat.yml
  .github/workflows/cilint-custom.yml
  .github/workflows/cilint.yml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yml
  .github/workflows/e2e.yml
  .github/workflows/release-operator.yaml
  Dockerfile
  Dockerfile.pause
  Dockerfile.tests
  api/numaresourcesoperator/v1alpha1/groupversion_info.go
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go
  pkg/k8sclientset/generated/clientset/versioned/fake/register.go
  pkg/k8sclientset/generated/clientset/versioned/scheme/register.go
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved

#477 Cleanup 20221128
  .github/workflows/release-operator.yaml
  Dockerfile.bundle
  Makefile
  README.md
  bundle.Dockerfile
Labels: approved, lgtm
