Repository openshift-kni/numaresources-operator, pull requests merged in 2022-04, with the labels that each got.

#241 serial: add events reporting for failing pods
  internal/baseload/baseload.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_placement_nodesel.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#233 hack: deploy MCO CRDs only if NOT on openshift
  Makefile
  hack/common.sh
  hack/deploy-mco-crds.sh
  hack/envsubst/envsubst.go
  hack/lsplatform/lsplatform.go
  hack/run-test-serial-e2e.sh
Labels: approved, lgtm

#246 vendor: bump rte deps 20220405
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/pods/rtepod/rtepod.go
  vendor/modules.txt
Labels: approved, lgtm

#240 project: misc cleanups
  controllers/kubeletconfig_controller_test.go
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller_test.go
  internal/baseload/baseload.go
  internal/baseload/baseload_test.go
  internal/objects/objects.go
  internal/resourcelist/resourcelist.go
  internal/resourcelist/resourcelist_test.go
  pkg/status/status_test.go
  pkg/validation/validation_test.go
  pkg/version/version_test.go
Labels: approved

#252 gh actions: add lane avoiding the gh actions lint
  .github/workflows/cilint-custom.yml
Labels: approved

#251 e2e: make `unschedulable` tests more robust
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/nrosched/nrosched.go
Labels: approved

#242 e2e: remove opt-in skip in the node-selector workload placement test
  test/e2e/serial/tests/workload_placement_nodesel.go
Labels: approved, lgtm

#254 e2e: serial: more robust untainting
  test/e2e/serial/tests/workload_placement_taint.go
Labels: approved, lgtm

#253 loglevel: rewrite log message
  pkg/loglevel/loglevel.go
Labels: approved, lgtm

#257 e2e: serial: config: clean up config API
  test/e2e/serial/config/config.go
  test/e2e/serial/config/fixture.go
Labels: approved, lgtm

#258 e2e: serial: config module modularization (take 2)
  test/e2e/serial/config/config.go
  test/e2e/serial/config/fixture.go
  test/e2e/serial/config/infra.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/sched_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodesel.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved

#259 e2e: serial: config: avoid NPE on teardown
  test/e2e/serial/config/config.go
Labels: approved

#256 e2e: serial: remove skip if `E2E_SERIAL_STAGING` variable set
  internal/baseload/baseload.go
  internal/resourcelist/resourcelist.go
  internal/resourcelist/resourcelist_test.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
Labels: approved, lgtm

#260 docs: document the CNF-tests integration
  README.md
Labels: approved

#261 e2e: tests documentation cleanup
  README.md
  README.tests.md
Labels: approved

#264 kubeletcontroller: minimize and tune reconciliation loop
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/kubeletconfig_controller.go
  test/e2e/rte/rte_test.go
Labels: approved, lgtm, cherry-pick-candidate

#262 e2e_test Daemonset partial available resources
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm, cherry-pick-candidate

#249 e2etest: TopoManager scope=pod two containers not sched
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm, cherry-pick-candidate

#255 e2e:serial: unschedulable numa level test
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm, cherry-pick-candidate

#265 serial: add tests for scheduling pod with nodeAffinity
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_nodesel.go
Labels: approved, lgtm, cherry-pick-candidate

#263 docs: fixes
  README.tests.md
Labels: approved, lgtm, do-not-merge/hold

#268 gh actions: trigger release also with -rc tags
  .github/workflows/release.yml
Labels: approved

#271 update OWNERS 20220421
  OWNERS_ALIASES
Labels: approved

#270 e2e serial fixes (20220421)
  test/e2e/serial/README.md
  test/e2e/serial/config/config.go
  test/e2e/serial/config/infra.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/images/images.go
  test/utils/objects/consts.go
  test/utils/objects/daemonset.go
  test/utils/objects/deployment.go
  test/utils/objects/objects.go
  test/utils/objects/pod.go
  test/utils/objects/wait/daemonset.go
  test/utils/objects/wait/deployment.go
  test/utils/objects/wait/errors.go
  test/utils/objects/wait/machineconfig.go
  test/utils/objects/wait/numaresources.go
  test/utils/objects/wait/paddingpods.go
  test/utils/objects/wait/pod.go
Labels: approved

#273 gh actions: add functionality to refresh the testsuite image
  .github/workflows/release-operator.yaml
  .github/workflows/release-testsuite.yaml
  Dockerfile.tests
Labels: approved

#276 e2e: serial: log pullSpec actually used
  test/e2e/serial/config/infra.go
  test/utils/images/images.go
Labels: approved, lgtm

#277 e2e: wait: terser logging when wait
  test/utils/objects/wait/daemonset.go
  test/utils/objects/wait/deployment.go
  test/utils/objects/wait/errors.go
  test/utils/objects/wait/machineconfig.go
  test/utils/objects/wait/numaresources.go
  test/utils/objects/wait/pod.go
Labels: approved, lgtm

#274 e2e: serial: make untainting more robust
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_taint.go
Labels: approved, lgtm

#279 documentation: explain how to run from the local tree
  README.tests.md
  hack/run-test-serial-e2e.sh
Labels: approved
