Repository openshift-kni/numaresources-operator, pull requests merged in 2023-10, with the labels that each got.

#689 Add golangci-lint
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  Makefile
  api/numaresourcesoperator/v1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_conversion.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  cmd/nrovalidate/main.go
  cmd/nrtcacheck/main.go
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  controllers/kubeletconfig_controller.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller.go
  internal/baseload/baseload.go
  internal/machineconfigpools/machineconfigpools.go
  internal/noderesourcetopology/tostring.go
  internal/noderesourcetopology/tostring_test.go
  internal/remoteexec/command.go
  internal/resourcelist/resourcelist.go
  internal/resourcelist/resourcelist_test.go
  internal/schedcache/synced.go
  internal/wait/job.go
  main.go
  pkg/flagcodec/flagcodec.go
  pkg/flagcodec/flagcodec_test.go
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/rte/rte_test.go
  pkg/objectupdate/sched/sched.go
  pkg/status/status.go
  pkg/validator/kubeletconfig.go
  pkg/validator/machineconfigpools.go
  pkg/validator/noderesourcetopologies.go
  pkg/validator/noderesourcetopologies_test.go
  pkg/validator/podstatus.go
  pkg/validator/validator.go
  pkg/validator/validator_test.go
  rte/main.go
  rte/pkg/config/config.go
  rte/pkg/config/config_test.go
  test/e2e/rte/rte_test.go
Labels: approved, lgtm

#701 serial: adjust NRT settle timeout and interval
  test/utils/fixture/fixture.go
Labels: approved, lgtm

#704 doc: fix examples
  doc/examples/sched.debug.yaml
  doc/examples/sched.nocache.yaml
Labels: approved, lgtm

#708 enable skipped tests & stabilize flaky tests
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/scheduler_cache.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#712 owners: update 20231012
  OWNERS_ALIASES
Labels: approved, lgtm

#716 golang: bump toolchain
  Dockerfile
  Dockerfile.pause
  Dockerfile.tests
  Dockerfile.tools
Labels: approved, lgtm

#723 operator: metrics: hooks: add disabling options
  main.go
Labels: approved, cherry-pick-candidate

#725 operator: enhance configurability
  main.go
Labels: approved, lgtm, cherry-pick-candidate

#727 rte: bump to 0.14.3
  go.mod
  go.sum
  rte/main.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/prometheus/prometheus.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#730 [release-4.13][manual] rte: bump to 0.11.5
  go.mod
  go.sum
  rte/main.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/prometheus/prometheus.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/topology_updater/topology_updater.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodes/nodes.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go
  vendor/modules.txt
Labels: approved, lgtm

#731 [release-4.12][manual] rte: bump to 0.11.5
  go.mod
  go.sum
  rte/main.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/prometheus/prometheus.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/topology_updater/topology_updater.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodes/nodes.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go
  vendor/modules.txt
Labels: approved, lgtm

#732 tests: minimize deps on k8s.io/kubernetes
  go.mod
  go.sum
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/fixture/wait.go
  vendor/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubectl/pkg/util/qos/qos.go
  vendor/k8s.io/kubectl/pkg/util/resource/resource.go
  vendor/k8s.io/kubernetes/pkg/api/v1/resource/helpers.go
  vendor/modules.txt
Labels: approved, cherry-pick-candidate

#737 e2e: Check Attributes when checking NRT mutation
  test/utils/noderesourcetopologies/noderesourcetopologies.go
Labels: approved, lgtm, cherry-pick-candidate

#738 envtest: bump to 1.27
  Makefile
Labels: approved, lgtm, cherry-pick-candidate

#743 [release-4.11] rte: disable metrics
  rte/main.go
Labels: approved, lgtm

#744 [release-4.11] metrics: add option to toggle on/off
  main.go
Labels: approved, lgtm

#745 [release-4.11] nrop: webhook: serve on localhost
  main.go
Labels: approved, lgtm

#747 snyk: e2e: ignore test code - unit and e2e
  .snyk
Labels: approved

#749 [release-4.13][manual] tests: minimize deps on k8s.io/kubernetes
  go.mod
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/fixture/wait.go
  vendor/k8s.io/kubectl/pkg/util/qos/qos.go
  vendor/k8s.io/kubectl/pkg/util/resource/resource.go
  vendor/k8s.io/kubernetes/pkg/api/v1/resource/helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#751 [release-4.12][manual] tests: minimize deps on k8s.io/kubernetes
  go.mod
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/fixture/wait.go
  vendor/k8s.io/kubectl/pkg/util/qos/qos.go
  vendor/k8s.io/kubectl/pkg/util/resource/resource.go
  vendor/k8s.io/kubernetes/pkg/api/v1/resource/helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#752 snyk: exclude stretchr testify-related repos
  .snyk
Labels: approved

#753 snyk: exclude deployer kubeletconfig package
  .snyk
Labels: approved

#746 k8s: taints: import package
  test/e2e/serial/tests/workload_placement_taint.go
  test/utils/k8simported/taints/LICENSE
  test/utils/k8simported/taints/README.md
  test/utils/k8simported/taints/helper.go
  test/utils/k8simported/taints/taints.go
  test/utils/k8simported/taints/taints_test.go
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#755 [release-4.13][manual] test: e2e: import and use the taints pkg from k8s
  test/e2e/serial/tests/workload_placement_taint.go
  test/utils/k8simported/taints/LICENSE
  test/utils/k8simported/taints/README.md
  test/utils/k8simported/taints/helper.go
  test/utils/k8simported/taints/taints.go
  test/utils/k8simported/taints/taints_test.go
Labels: approved

#758 lint: e2e: e2e tests should be linted
  .golangci.yaml
Labels: approved, lgtm

#759 controller: minimize related object list
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
Labels: approved, lgtm, cherry-pick-candidate
