Repository openshift-kni/numaresources-operator, pull requests merged in 2023-06, with the labels that each got.

#587 api: scheduler: add tunable for dedicated informer
  api/numaresourcesoperator/v1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_normalize.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_normalize_test.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  pkg/objectupdate/rte/rte_test.go
  pkg/objectupdate/sched/sched.go
  pkg/objectupdate/sched/sched_test.go
  test/e2e/serial/tests/scheduler_cache.go
Labels: approved

#590 rte: revert to "method=all" PFP by default
  api/numaresourcesoperator/v1/numaresourcesoperator_defaults.go
  api/numaresourcesoperator/v1/numaresourcesoperator_defaults_test.go
  api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go
  pkg/objectupdate/rte/rte_test.go
Labels: approved, cherry-pick-candidate

#596 deps: bump RTE to v0.11.2
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#595 manifests: drop obsolete node-role labels
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/nodes/nodes.go
  pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
Labels: approved, cherry-pick-candidate

#602 e2e: serial improve logs
  internal/noderesourcetopology/tostring.go
  test/e2e/serial/config/infra.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/objects/pod.go
  test/utils/padder/padder.go
Labels: approved, cherry-pick-candidate

#598 e2e: serial: resacct improve and generalize expectations
  internal/wait/noderesourcetopologies.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/helper/attribute/attribute.go
  vendor/modules.txt
Labels: approved, lgtm, do-not-merge/hold, cherry-pick-candidate

#608 e2e: serial: resacct improve and generalize expectations, take 2
  internal/wait/noderesourcetopologies.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
Labels: approved, lgtm, cherry-pick-candidate

#614 ghactions: kind: update image
  .github/workflows/e2e-tools.yml
  .github/workflows/e2e.yml
Labels: approved, lgtm, cherry-pick-candidate

#617 project: layout: move helpers in `cmd/`
  Makefile
  cmd/nrovalidate/main.go
  cmd/nrtcacheck/main.go
  cmd/numaresources-operator/README.md
  cmd/resource-topology-exporter/README.md
Labels: approved

#594 e2e: serial: kickoff tests for scheduler stall
  internal/wait/job.go
  pkg/objectupdate/sched/sched.go
  pkg/objectupdate/sched/sched_test.go
  test/e2e/serial/tests/scheduler_cache.go
  test/e2e/serial/tests/scheduler_cache_stall.go
Labels: approved, cherry-pick-candidate

#623 e2e: print random seed being used
  test/e2e/rte/rte_e2e_suite_test.go
  test/e2e/serial/e2e_serial_test.go
Labels: approved, lgtm, cherry-pick-candidate

#610 e2e: verify nrt data after each test
  test/e2e/serial/README.md
  test/e2e/serial/config/fixture.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/non_regression_fundamentals.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/scheduler_cache.go
  test/e2e/serial/tests/scheduler_cache_stall.go
  test/e2e/serial/tests/scheduler_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/fixture/fixture.go
Labels: approved, lgtm

#629 e2e: add missing wait for NRT to settle
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm

#628 e2e cleanup 20230628
  internal/noderesourcetopology/equality.go
  internal/noderesourcetopology/equality_test.go
  internal/noderesourcetopology/sorted.go
  internal/noderesourcetopology/sorted_test.go
  internal/wait/noderesourcetopologies.go
  test/deviceplugin/pkg/numacell/api/numacell.go
  test/e2e/serial/README.md
  test/e2e/serial/config/config.go
  test/e2e/serial/config/fixture.go
  test/e2e/serial/config/infra.go
  test/utils/fixture/fixture.go
Labels: approved, lgtm, cherry-pick-candidate
