Repository openshift-kni/numaresources-operator, pull requests merged in 2023-11, with the labels that each got.

#765 chore: lint: fixes 20231107
  test/deviceplugin/pkg/numacell/plugin/numacell.go
  test/e2e/install/install_test.go
  test/e2e/must-gather/must_gather_suite_test.go
  test/e2e/must-gather/must_gather_test.go
  test/e2e/rte/rte_test.go
  test/e2e/sched/sched_test.go
  test/e2e/serial/config/config.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/scheduler_cache.go
  test/e2e/serial/tests/scheduler_cache_stall.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/e2e/tools/nrovalidate_test.go
  test/utils/deploy/deploy.go
  test/utils/fixture/fixture.go
  test/utils/fixture/node_selection.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  test/utils/nrosched/nrosched.go
  test/utils/padder/padder.go
Labels: approved, lgtm

#764 deployer: upgrade to v0.15.z
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/flagcodec/flagcodec_test.go
  pkg/loglevel/loglevel.go
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/sched/sched.go
  test/e2e/install/install_test.go
  test/e2e/rte/rte_test.go
  test/e2e/serial/tests/workload_placement.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/rte/assets.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/rte/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/assets.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.10.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.11.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.12.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.13.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/selinuxinstall.service.template
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/deployer.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/detect/detect.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/daemonset.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/deployment.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/wait.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/flagcodec/flagcodec.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/images.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/output.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/kubeletconfig/configz.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/api/api.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/manifests.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/topologyupdater/daemonset.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/daemonset.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/affinity.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/find.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/sched/sched.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/types.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#767 e2e: serial: remove half-baked randomSeed
  test/e2e/serial/e2e_serial_test.go
Labels: approved, lgtm

#766 e2e: serial: rewrite deployment wait
  test/e2e/serial/tests/scheduler_removal.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/daemonset.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/deployment.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/wait.go
  vendor/modules.txt
Labels: approved

#773 serial: remove ReporterAfterSuite to fix linter
  test/e2e/serial/e2e_serial_test.go
Labels: approved, lgtm

#774 [release-4.13][manual] Deprecate TopologyPolicies field
  internal/noderesourcetopology/attributes.go
  internal/noderesourcetopology/tostring.go
  internal/noderesourcetopology/tostring_test.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  test/utils/nrosched/nrosched.go
  test/utils/padder/padder.go
Labels: approved, lgtm

#777 [release-4.12] deps: k8s: bump to 1.25.z latest
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/modules.txt
Labels: approved

#776 vendor: remove unused deps
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, lgtm

#775 e2e: serial: more precise skip location
  test/utils/fixture/fixture.go
Labels: approved, lgtm, cherry-pick-candidate

#779 controller: test: don't update objects via status()
  controllers/numaresourcesoperator_controller_test.go
Labels: approved, cherry-pick-candidate

#789 improve test coverage 20231115
  controllers/numaresourcesoperator_controller_test.go
  internal/relatedobjects/objects_test.go
  pkg/objectstate/objectstate_test.go
  pkg/objectstate/rte/rte_test.go
  test/utils/configuration/configuration.go
Labels: approved

#686 modified render to add must-gather tests
  Dockerfile.tests
  hack/render-e2e-runner.sh
  hack/run-test-must-gather-e2e.sh
  hack/run-test-tools-e2e.sh
Labels: approved, lgtm, ok-to-test

#790 controller: test: relax condition
  controllers/numaresourcesoperator_controller_test.go
Labels: approved, lgtm, cherry-pick-candidate

#795 [release-4.14][manual] deployer: upgrade to v0.15.z
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/flagcodec/flagcodec_test.go
  pkg/loglevel/loglevel.go
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/sched/sched.go
  test/e2e/install/install_test.go
  test/e2e/rte/rte_test.go
  test/e2e/serial/tests/workload_placement.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/rte/assets.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/rte/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/assets.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.10.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.11.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.12.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.13.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/selinuxinstall.service.template
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/deployer.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/detect/detect.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/daemonset.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/deployment.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/wait.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/flagcodec/flagcodec.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/images.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/output.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/kubeletconfig/configz.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/api/api.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/manifests.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/topologyupdater/daemonset.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/daemonset.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/affinity.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/find.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/sched/sched.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/types.go
  vendor/modules.txt
Labels: approved

#796 sched: manifests: move to v1beta3 for the config
  pkg/numaresourcesscheduler/manifests/yaml/configmap.nrt.yaml
  pkg/numaresourcesscheduler/objectstate/sched/sched_test.go
  pkg/objectupdate/sched/fakeconfs.go
Labels: approved

#797 [release-4.14][manual] cumulative backport of test-related enhancements
  Makefile
  go.mod
  go.sum
  test/e2e/serial/e2e_serial_test.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved
