Repository openshift-kni/numaresources-operator, pull requests merged in 2023-12, with the labels that each got.

#803 flagcodec: always use flag normalization
  go.mod
  go.sum
  pkg/loglevel/loglevel.go
  pkg/loglevel/loglevel_test.go
  pkg/objectupdate/rte/rte.go
  test/e2e/rte/rte_test.go
  test/e2e/serial/tests/workload_placement.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/flagcodec/flagcodec.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/schedparams.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/sched/render.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#802 e2e: serial: resource accounting: take cluster snapshot post padding
  go.mod
  go.sum
  internal/noderesourcetopology/equality.go
  internal/wait/noderesourcetopologies.go
  test/e2e/serial/config/fixture.go
  test/e2e/serial/tests/resource_accounting.go
  test/utils/fixture/fixture.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/sysinfo/hugepages.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/sysinfo/memory.go
  vendor/modules.txt
Labels: approved

#805 support error reporting & increae default cooldown timeout
  test/utils/fixture/fixture.go
Labels: approved, lgtm
