Repository openshift-kni/numaresources-operator, pull requests merged in 2023-01, with the labels that each got.

#497 update: deployer v0.10.1, scheduler-plugins v0.24.9
  controllers/numaresourcesscheduler_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/objectupdate/sched/codec.go
  pkg/objectupdate/sched/sched.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/deployer.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/detect/autoselection.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/daemonset.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/deployment.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/wait.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/kubeletconfig/configz.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/kubeletconfig/kubectl.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/api/api.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/codec.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/manifests.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/updates.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/master/clusterrole.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/master/clusterrolebinding.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/master/deployment.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/master/service.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/master/serviceaccount.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/topologyupdater/clusterrole.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/nfd/topologyupdater/daemonset.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/sched/configmap.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/sched/scheduler/deployment.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/tlog/tlog.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/validator/kubeletconfig.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/validator/validator.go
  vendor/modules.txt
Labels: approved, lgtm

#502 chore: internal: rename import to nropv1alpha1
  controllers/kubeletconfig_controller_test.go
  controllers/numaresourcesoperator_controller_test.go
  internal/objects/objects.go
Labels: approved, lgtm, cherry-pick-candidate

#503 [manual][release-4.12] chore: internal: rename import to nropv1alpha1
  controllers/kubeletconfig_controller_test.go
  controllers/numaresourcesoperator_controller_test.go
  internal/objects/objects.go
Labels: approved, lgtm

#504 reorganize the machineconfigpools package
  api/numaresourcesoperator/v1alpha1/helper/nodegroup/nodegroup.go
  api/numaresourcesoperator/v1alpha1/helper/nodegroup/nodegroup_test.go
  controllers/kubeletconfig_controller.go
  controllers/numaresourcesoperator_controller.go
  internal/machineconfigpools/machineconfigpools.go
  pkg/machineconfigpools/machineconfigpools.go
  pkg/normalize/normalize.go
  pkg/normalize/normalize_test.go
  pkg/objectstate/rte/rte.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
  pkg/validator/kubeletconfig.go
  pkg/validator/machineconfigpools.go
  pkg/validator/validator.go
  test/e2e/rte/rte_test.go
  test/e2e/serial/config/infra.go
  test/e2e/serial/tests/configuration.go
  test/e2e/uninstall/uninstall_test.go
  test/utils/deploy/deploy.go
  test/utils/objects/pause/mcps.go
Labels: approved, lgtm, cherry-pick-candidate

#507 api: nodegroup: fix loop invariant
  api/numaresourcesoperator/v1alpha1/helper/nodegroup/nodegroup.go
Labels: approved, cherry-pick-candidate

#509 hack: update boilerplate.go.txt
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  hack/boilerplate.go.txt
Labels: approved, lgtm, cherry-pick-candidate

#511 chore: make the api package import rename uniform
  controllers/controllers_suite_test.go
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
  pkg/numaresourcesscheduler/objectstate/sched/sched_test.go
  test/utils/clients/clients.go
Labels: approved, cherry-pick-candidate

#512 [release-4.12][manual] chore: make the api package import rename uniform
  controllers/controllers_suite_test.go
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
  pkg/numaresourcesscheduler/objectstate/sched/sched_test.go
  test/utils/clients/clients.go
Labels: approved, lgtm

#514 hack: boilerplate: fix copyright year positioning
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  hack/boilerplate.go.txt
Labels: approved

#521 [release-4.10][manual] gh actions: add functionality to refresh the testsuite image
  .github/workflows/release-operator.yaml
  .github/workflows/release-testsuite.yaml
  Dockerfile.tests
Labels: approved

#522 Update prow configuration 20230131
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm
