Repository openshift-kni/numaresources-operator, pull requests merged in 2023-05, with the labels that each got.

#552 e2e: nrosched: add extra logs and filters
  test/utils/nrosched/nrosched.go
Labels: approved, lgtm

#554 csv: fix operator maturity alpha->stable
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#553 deps: rte: bump and adapt to 0.11.1
  go.mod
  go.sum
  rte/main.go
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/kubeconf/kubelet_config_file.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/client.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/filter/alwayspass.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/filter/numalocality/numalocality.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/middleware/podexclude/podexclude.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/middleware/sharedcpuspool/sharedcpuspool.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/mock_PodResourcesListerClient.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourceobserver.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go
  vendor/github.com/stretchr/objx/.codeclimate.yml
  vendor/github.com/stretchr/objx/.gitignore
  vendor/github.com/stretchr/objx/LICENSE
  vendor/github.com/stretchr/objx/README.md
  vendor/github.com/stretchr/objx/Taskfile.yml
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/objx/conversions.go
  vendor/github.com/stretchr/objx/doc.go
  vendor/github.com/stretchr/objx/map.go
  vendor/github.com/stretchr/objx/mutations.go
  vendor/github.com/stretchr/objx/security.go
  vendor/github.com/stretchr/objx/tests.go
  vendor/github.com/stretchr/objx/type_specific.go
  vendor/github.com/stretchr/objx/type_specific_codegen.go
  vendor/github.com/stretchr/objx/value.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#556 scheduler: enable reserve plugin and cache by default
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  pkg/objectupdate/sched/compat.go
  pkg/objectupdate/sched/compat_test.go
  pkg/objectupdate/sched/fakeconfs.go
  pkg/objectupdate/sched/sched.go
  pkg/objectupdate/sched/sched_test.go
Labels: approved, lgtm, cherry-pick-candidate

#560 deps: explicit require
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#562 rte: enable PFP computation considering only pods with exclusive resources assigned
  api/numaresourcesoperator/v1/numaresourcesoperator_defaults.go
  api/numaresourcesoperator/v1/numaresourcesoperator_defaults_test.go
  api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go
  api/numaresourcesoperator/v1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_conversion.go
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/rte/rte_test.go
  test/e2e/serial/tests/scheduler_cache.go
Labels: approved, lgtm

#558 validator: add validation for scheduler cache
  Makefile
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesscheduler_controller.go
  doc/examples/sched.debug.yaml
  internal/remoteexec/command.go
  internal/schedcache/synced.go
  nrtcacheck/main.go
  pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
  pkg/objectupdate/sched/sched.go
  pkg/objectupdate/sched/sched_test.go
  pkg/validator/schedcache.go
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: approved, cherry-pick-candidate

#570 nrtcacheck: add option to dump node states
  go.mod
  internal/schedcache/synced.go
  nrtcacheck/main.go
  pkg/validator/schedcache.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
Labels: approved, cherry-pick-candidate

#573 cleanup 20230523
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
Labels: approved, cherry-pick-candidate

#563 serial: fix reboot testcase and properly wait on mcp updates
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#586 ghactions: update base actions
  .github/workflows/cibuild.yml
  .github/workflows/ciformat.yml
  .github/workflows/cilint-custom.yml
  .github/workflows/cilint.yml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yml
  .github/workflows/e2e.yml
  .github/workflows/release-operator.yaml
  .github/workflows/release-testsuite.yaml
Labels: approved, lgtm
