Repository openshift-kni/numaresources-operator, pull requests merged in 2023-07, with the labels that each got.

#606 e2e: serial: Fail fast if policies not aligned
  pkg/validator/validator.go
  test/e2e/serial/config/config.go
  test/e2e/serial/e2e_serial_test.go
Labels: approved, lgtm

#634 nrtcacheck: use v1 API
  cmd/nrtcacheck/main.go
Labels: approved

#633 must-gather: debuggability updates
  Makefile
  test/e2e/must-gather/README.md
  test/e2e/must-gather/must_gather_suite_test.go
  test/e2e/must-gather/must_gather_test.go
  test/utils/deploy/deploy.go
Labels: approved, lgtm, cherry-pick-candidate

#635 e2e: serial: support kubelet defaults in validation
  test/e2e/serial/config/config.go
Labels: approved, lgtm

#639 operator: rte: default inforefreshmode=periodic
  api/numaresourcesoperator/v1/numaresourcesoperator_defaults.go
  api/numaresourcesoperator/v1/numaresourcesoperator_defaults_test.go
  api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go
  controllers/numaresourcesoperator_controller_test.go
  pkg/objectupdate/rte/rte_test.go
Labels: approved, lgtm, cherry-pick-candidate

#640 serial: fetch CacheResyncPeriod from Status
  test/e2e/serial/tests/non_regression_fundamentals.go
  test/e2e/serial/tests/scheduler_cache_stall.go
Labels: approved, lgtm, cherry-pick-candidate

#646 e2e: run scheduler tests by default
  hack/run-test-e2e.sh
Labels: approved, lgtm

#638 Makefile: build: use shared libraries
  Makefile
Labels: approved, lgtm

#647 internal: drop stale v1alpha1 API ref
  internal/schedcache/synced.go
Labels: approved, cherry-pick-candidate

#645 e2e:scheduler: verify cacheResyncPeriod settings
  test/e2e/sched/sched_test.go
Labels: approved, lgtm, cherry-pick-candidate

#655 deps: bump to k8s 1.25.11
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#659 serial: fix nil pointer in log
  test/e2e/serial/config/config.go
Labels: approved, lgtm

#661 base image: ubi8 to ubi9
  Dockerfile
  Dockerfile.must-gather
  Dockerfile.openshift
  Dockerfile.openshift.rte
  Dockerfile.openshift.tests
  Dockerfile.pause
  Dockerfile.tests
  Dockerfile.tools
  test/deviceplugin/cmd/numacell/Dockerfile
Labels: approved, lgtm

#662 golang: move to 1.20
  .github/workflows/cibuild.yml
  .github/workflows/ciformat.yml
  .github/workflows/cilint-custom.yml
  .github/workflows/cilint.yml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yml
  .github/workflows/e2e.yml
  .github/workflows/release-operator.yaml
  Dockerfile
  Dockerfile.pause
  Dockerfile.tests
  Dockerfile.tools
  go.mod
Labels: approved, lgtm

#664 Dockerfile: tools: drop python2
  Dockerfile.tools
Labels: approved

#668 e2e: build: use fully static build for serial
  Makefile
Labels: approved, lgtm

#667 Makefile: split test-unit
  Makefile
Labels: approved, lgtm, cherry-pick-candidate

#658 controllers: add related-objects support
  api/numaresourcesoperator/v1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
Labels: approved, lgtm, cherry-pick-candidate

#652 Deprecate topology policies
  internal/noderesourcetopology/attributes.go
  internal/noderesourcetopology/tostring.go
  internal/noderesourcetopology/tostring_test.go
  test/e2e/serial/config/config.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
  test/utils/nrosched/nrosched.go
  test/utils/padder/padder.go
Labels: approved, lgtm, cherry-pick-candidate

#653 e2e: fix RTE lane
  .github/workflows/e2e.yml
  Makefile
  hack/kind-config-e2e-no-registry.yaml
  hack/run-test-e2e.sh
  rte/hack/deploy-devices.sh
  rte/hack/manifests/sample-devices/configmap-dpa.yaml
  rte/hack/manifests/sample-devices/daemonset-dpa.yaml
  rte/hack/manifests/sample-devices/namespace.yaml
  rte/hack/manifests/sample-devices/role.yaml
  rte/hack/manifests/sample-devices/rolebinding.yaml
  rte/hack/manifests/sample-devices/serviceaccount.yaml
  rte/hack/undeploy-devices.sh
  test/e2e/rte/rte_e2e_suite_test.go
  test/e2e/rte/rte_local_test.go
  tools/catkubeletconfmap/catkubeletconfmap.go
Labels: approved, lgtm, cherry-pick-candidate

#673 tools: add license boilerplate
  tools/buildhelper/buildhelper.go
  tools/catkubeletconfmap/catkubeletconfmap.go
  tools/envsubst/envsubst.go
  tools/lsplatform/lsplatform.go
Labels: approved, lgtm

#674 sysinfo and podrescompat removal: superseded by getallocatableResources
  go.mod
  rte/hack/setup-e2e.sh
  rte/main.go
  rte/pkg/config/config.go
  rte/pkg/config/config_test.go
  rte/pkg/podrescompat/client.go
  rte/pkg/podrescompat/client_test.go
  rte/pkg/sysinfo/sysinfo.go
  rte/pkg/sysinfo/sysinfo_test.go
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm, cherry-pick-candidate

#675 rte: remove more dead code
  go.mod
  rte/main.go
  rte/pkg/config/config.go
  rte/pkg/podresfilter/client.go
  rte/pkg/podresfilter/client_test.go
Labels: approved, lgtm
