Repository openshift-kni/numaresources-operator, pull requests merged in 2024-11, with the labels that each got.

#1060 e2e: fix padder allocationTarget to ensure unfeasible nodes
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/utils/padder/padder.go
Labels: approved, lgtm

#1061 manifests: relax node affinity for hypershift
  config/manager/manager.yaml
  pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
Labels: approved, lgtm

#1062 CI: Update github actions versions
  .github/workflows/ci.yaml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yaml
  .github/workflows/e2e.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/release-operator.yaml
  .github/workflows/release-testsuite.yaml
  .github/workflows/support-tools.yaml
Labels: approved, lgtm

#1064 controller: handle dangling ds when using poolname
  internal/dangling/dangling.go
Labels: approved, lgtm

#1067 deploy-mco-crds.sh: do not install mco crds on hypershift
  hack/deploy-mco-crds.sh
Labels: approved, lgtm

#1066 validation: ensure non-empty poolName
  internal/dangling/dangling.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
Labels: approved, lgtm

#1068 e2e: mustgather: fix test to verify TAS enabled nodes only
  test/e2e/must-gather/must_gather_test.go
Labels: approved, lgtm

#1072 Bump golang build 1.23
  .github/workflows/ci.yaml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yaml
  .github/workflows/e2e.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/release-operator.yaml
  .github/workflows/support-tools.yaml
  Dockerfile
  Dockerfile.pause
  Dockerfile.tests
  Dockerfile.tools
Labels: approved, lgtm

#1077 bump OPM: 1.15 -> 1.48
  Makefile
Labels: approved, lgtm

#1079 sched: manifests: disable leader election by default
  pkg/numaresourcesscheduler/manifests/yaml/configmap.nrt.yaml
Labels: approved, lgtm, cherry-pick-candidate

#1015 CNF-11193: controller:hypershift: add support in for Kubelet controller
  controllers/kubeletconfig_controller.go
  controllers/kubeletconfig_controller_test.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  internal/objects/objects.go
  main.go
Labels: approved, lgtm

#1032 cleanup and streamline status computation
  controllers/controllers.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller.go
  internal/reconcile/step.go
  pkg/status/conditioninfo/conditioninfo.go
  pkg/status/status.go
  pkg/status/status_test.go
Labels: approved, lgtm

#1027 ctrl: HCP adaptations for NodeGroup validation and RTE
  api/numaresourcesoperator/v1/helper/nodegroup/nodegroup.go
  api/numaresourcesoperator/v1/helper/nodegroup/nodegroup_test.go
  controllers/numaresourcesoperator_controller.go
  pkg/objectstate/rte/rte.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
Labels: approved, lgtm

#1084 add the internal/kloglevel package
  internal/kloglevel/kloglevel.go
  main.go
  tools/nrtcacheck/nrtcacheck.go
Labels: approved

#1083 Support NROP controller tests on hypershift
  controllers/numaresourcesoperator_controller_test.go
  internal/objects/objects.go
Labels: approved, lgtm

#1063 mustgather: Dockerfile: use ocp CLI base image
  Dockerfile.must-gather
Labels: approved, lgtm, cherry-pick-candidate

#1069 Add missing controller test for PoolName
  controllers/numaresourcesoperator_controller_test.go
Labels: approved, lgtm

#1087 [release-4.17][manual] sched: always set the leader election parameters
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  pkg/numaresourcesscheduler/consts.go
  pkg/status/status.go
Labels: approved, lgtm

#1088 CNF-15733:kubeletcontroller:hypershift: configmap cleanup
  controllers/kubeletconfig_controller.go
  test/utils/deploy/hypershift.go
Labels: approved, lgtm

#1089 tests: add coverage report and increase coverage
  .gitignore
  Makefile
  go.mod
  go.sum
  internal/reconcile/step_test.go
  pkg/hash/configmap.go
  pkg/hash/configmap_test.go
  pkg/numaresourcesscheduler/consts_test.go
  pkg/numaresourcesscheduler/controlplane/discover_test.go
  pkg/status/conditioninfo/conditioninfo_test.go
  pkg/status/status.go
  pkg/status/status_test.go
  vendor/github.com/asaskevich/govalidator/.gitignore
  vendor/github.com/asaskevich/govalidator/.travis.yml
  vendor/github.com/asaskevich/govalidator/CODE_OF_CONDUCT.md
  vendor/github.com/asaskevich/govalidator/CONTRIBUTING.md
  vendor/github.com/asaskevich/govalidator/LICENSE
  vendor/github.com/asaskevich/govalidator/README.md
  vendor/github.com/asaskevich/govalidator/arrays.go
  vendor/github.com/asaskevich/govalidator/converter.go
  vendor/github.com/asaskevich/govalidator/doc.go
  vendor/github.com/asaskevich/govalidator/error.go
  vendor/github.com/asaskevich/govalidator/numerics.go
  vendor/github.com/asaskevich/govalidator/patterns.go
  vendor/github.com/asaskevich/govalidator/types.go
  vendor/github.com/asaskevich/govalidator/utils.go
  vendor/github.com/asaskevich/govalidator/validator.go
  vendor/github.com/asaskevich/govalidator/wercker.yml
  vendor/modules.txt
Labels: approved

#1091 e2e: more robust wait for MCP updates
  internal/wait/kubeletconfig.go
  internal/wait/machineconfigpool.go
  test/e2e/install/install_test.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/tolerations.go
  test/e2e/uninstall/uninstall_test.go
  test/utils/deploy/deploy.go
  test/utils/deploy/openshift.go
Labels: approved, lgtm

#1093 controller: nrop: always populate reason (progressing)
  controllers/numaresourcesoperator_controller.go
  internal/reconcile/step.go
  pkg/status/conditioninfo/conditioninfo.go
Labels: approved, lgtm
