Repository openshift-kni/numaresources-operator, pull requests merged in 2024-04, with the labels that each got.

#901 controller: fix daemonUpdater
  controllers/numaresourcesoperator_controller.go
Labels: approved, lgtm, cherry-pick-candidate

#903 [release-4.14][manual] kubeletconfig: ignore nonmatching kubeletconfig objects
  controllers/kubeletconfig_controller.go
  controllers/kubeletconfig_controller_test.go
  internal/machineconfigpools/machineconfigpools.go
  internal/machineconfigpools/machineconfigpools_test.go
  internal/objects/objects.go
  internal/wait/kubeletconfig.go
  rte/pkg/config/config.go
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#905 internal: expose function to list all pods on a node
  internal/nodes/nodes.go
  internal/podlist/node.go
  test/e2e/rte/rte_test.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm

#906 [release-4.13][manual] kubeletconfig: ignore nonmatching kubeletconfig objects
  controllers/kubeletconfig_controller.go
  controllers/kubeletconfig_controller_test.go
  internal/machineconfigpools/machineconfigpools.go
  internal/machineconfigpools/machineconfigpools_test.go
  internal/objects/objects.go
  internal/wait/kubeletconfig.go
  rte/pkg/config/config.go
  test/e2e/serial/tests/configuration.go
Labels: approved

#908 [release-4.12][manual] kubeletconfig: ignore nonmatching kubeletconfig objects
  controllers/kubeletconfig_controller.go
  controllers/kubeletconfig_controller_test.go
  internal/machineconfigpools/machineconfigpools.go
  internal/machineconfigpools/machineconfigpools_test.go
  internal/objects/objects.go
  internal/wait/kubeletconfig.go
  rte/pkg/config/config.go
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#895 CNF-11848: [release-4.15][manual] RTE: add support to add extra tolerations
  api/numaresourcesoperator/v1/numaresourcesoperator_normalize.go
  api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go
  api/numaresourcesoperator/v1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_conversion.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  internal/wait/daemonset.go
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/rte/rte_test.go
  test/e2e/serial/tests/tolerations.go
  test/e2e/serial/tests/workload_placement_taint.go
Labels: approved, lgtm

#910 e2e: wait for ds creation before checking it is ready
  test/e2e/serial/tests/tolerations.go
Labels: approved, lgtm

#913 [release-4.15] manual cherry-pick of 900,910,912
  internal/podlist/node.go
  internal/wait/daemonset.go
  test/e2e/serial/tests/tolerations.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm

#918 e2e: tolerations: test CR and taint updates
  test/e2e/serial/tests/tolerations.go
Labels: approved, lgtm, cherry-pick-candidate

#919 e2e: fix toleration tests flakes
  internal/wait/daemonset.go
  test/e2e/serial/tests/tolerations.go
Labels: approved, lgtm

#916 CVE-2023-45288: deps: bump x/net and related
  go.mod
  go.sum
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
Labels: approved, do-not-merge/hold

#924 openshift: crd: update to deal with latest CRDs
  .github/workflows/e2e-tools.yml
  .github/workflows/e2e.yml
  Makefile
  hack/deploy-mco-crds.sh
Labels: approved, lgtm, cherry-pick-candidate

#925 e2e: sched: ensure updates are retried
  test/e2e/sched/sched_test.go
Labels: approved
