Repository openshift-kni/numaresources-operator, pull requests merged in 2024-07, with the labels that each got.

#949 numaresources: cleanup and modularize controller
  controllers/kubeletconfig_controller.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesscheduler_controller.go
  doc/examples/pod.ephstor.yaml
  pkg/apply/apply.go
  pkg/apply/apply_test.go
Labels: approved, lgtm, cherry-pick-candidate

#950 host-level and reboot-required tests stablization
  go.mod
  go.sum
  internal/wait/pod.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/resource_hostlevel.go
  test/e2e/serial/tests/tolerations.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/modules.txt
Labels: approved, lgtm

#952 [release-4.15][manual] improve support to coexist with standard scheduler
  api/numaresourcesoperator/v1/numaresourcesscheduler_normalize.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_normalize_test.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  test/e2e/serial/tests/scheduler_cache.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
Labels: approved, lgtm

#956 hack: workflow: support multiple commit authors
  hack/verify-commits.sh
  tools/verify-commit/verify-commit.go
Labels: approved

#955 e2e: align tags and labels
  hack/run-test-serial-e2e.sh
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/non_regression_fundamentals.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/resource_hostlevel.go
  test/e2e/serial/tests/scheduler_cache.go
  test/e2e/serial/tests/scheduler_cache_stall.go
  test/e2e/serial/tests/scheduler_removal.go
  test/e2e/serial/tests/tolerations.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_no_nrt.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
Labels: approved, lgtm

#954 [release-4.14][manual] improve support to coexist with standard scheduler
  api/numaresourcesoperator/v1/numaresourcesscheduler_normalize.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_normalize_test.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
Labels: approved, lgtm

#963 manifests: label: add `app` label
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, cherry-pick-candidate

#961 e2e: add test scheduler picks TM policy update without need to restart
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#958 e2e: manager: add features introspection
  .github/workflows/e2e-tools.yml
  .github/workflows/support-tools.yml
  Makefile
  doc/features/README.md
  internal/api/features/_topics.json
  internal/api/features/topics.go
  internal/api/features/topics_test.go
  internal/api/features/types.go
  internal/api/features/types_test.go
  main.go
  test/e2e/serial/README.md
  test/e2e/serial/e2e_serial_test.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/non_regression_fundamentals.go
  test/e2e/serial/tests/resource_accounting.go
  test/e2e/serial/tests/resource_hostlevel.go
  test/e2e/serial/tests/scheduler_cache.go
  test/e2e/serial/tests/scheduler_cache_stall.go
  test/e2e/serial/tests/scheduler_removal.go
  test/e2e/serial/tests/tolerations.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_placement_no_nrt.go
  test/e2e/serial/tests/workload_placement_nodelabel.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_taint.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/e2e/tools/mkginkgolabelfilter_test.go
  test/e2e/tools/tools_test.go
  tools/mkginkgolabelfilter/mkginkgolabelfilter.go
Labels: approved, lgtm
