Repository openshift-kni/numaresources-operator, pull requests merged in 2024-12, with the labels that each got.

#1095 rte: consume dep v0.20.z
  controllers/kubeletconfig_controller.go
  go.mod
  go.sum
  internal/wait/mcp.go
  internal/wait/nrts.go
  rte/main.go
  rte/pkg/config/config.go
  rte/pkg/config/config_test.go
  test/e2e/rte/local/local.go
  test/e2e/rte/rte_test.go
  test/e2e/serial/tests/configuration.go
  test/utils/configuration/configuration.go
  test/utils/deploy/deploy.go
  test/utils/deploy/openshift.go
  test/utils/noderesourcetopologies/nrts.go
  test/utils/noderesourcetopologies/nrts_test.go
  tools/catkubeletconfmap/catkubeletconfmap.go
  vendor/github.com/jeremywohl/flatten/v2/LICENSE
  vendor/github.com/jeremywohl/flatten/v2/README.md
  vendor/github.com/jeremywohl/flatten/v2/doc.go
  vendor/github.com/jeremywohl/flatten/v2/flatten.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/config/cfgdispatch.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/config/cfgfile.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/config/config.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/config/defaults.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/config/environ.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/config/flags.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/config/validation.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/k8sannotations/annotations.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/k8simported/cpuset/cpuset.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/metrics/metrics.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/metrics/server/setup.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/notification/notification.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/client.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/fake.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/middleware/podexclude/podexclude.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/middleware/sharedcpuspool/sharedcpuspool.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/middleware/terminalpods/terminalpods.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/podres/mock_PodResourcesListerClient.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/version/version.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/remoteexec/command.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go
  vendor/modules.txt
Labels: approved

#1099 e2e: test: introduce workarounds
  .snyk
  internal/workarounds/interface.go
  internal/workarounds/prom.go
  internal/workarounds/prom_test.go
  test/e2e/install/install_test.go
Labels: approved, lgtm

#1098 Separated NROP uninstall from install script
  Makefile
  hack/run-test-install-e2e.sh
  hack/run-test-uninstall-e2e.sh
Labels: approved, lgtm

#1100 gosec: initial scaffolding
  Makefile
  pkg/objectupdate/sched/fakeconfs.go
  rte/pkg/config/config.go
  rte/pkg/config/config_test.go
Labels: approved

#1102 NO-JIRA: controller:annotation: introduce pause annotation
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller.go
  internal/api/annotations/annotations.go
  internal/api/annotations/annotations_test.go
Labels: approved, lgtm, cherry-pick-candidate

#1105 tree: version: move to 4.19
  .github/workflows/release-testsuite.yaml
  Dockerfile.must-gather
  Makefile
  README.tests.md
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  config/samples/nodetopology_v1_numaresourcesscheduler.yaml
  config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml
  doc/examples/sched.debug.yaml
  doc/examples/sched.ha.yaml
  doc/examples/sched.nocache.yaml
  doc/examples/sched.yaml
  internal/api/features/types.go
  test/e2e/must-gather/must_gather_suite_test.go
  test/utils/objects/objects.go
Labels: approved, lgtm

#1101 add static buildinfo information
  Dockerfile
  Dockerfile.openshift
  Dockerfile.openshift.rte
  Makefile
  main.go
  pkg/version/version.go
  rte/main.go
  tools/buildhelper/buildhelper.go
Labels: approved

#1110 ghactions: enable on stable branches
  .github/workflows/ci.yaml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yaml
  .github/workflows/e2e.yaml
  .github/workflows/golangci-lint.yaml
Labels: approved, cherry-pick-candidate, cherry-pick-approved

#1109 [release-4.17][manual] NO-JIRA: controller:annotation: introduce pause annotation
  .snyk
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  controllers/numaresourcesscheduler_controller.go
  internal/api/annotations/annotations.go
  internal/api/annotations/annotations_test.go
Labels: approved, lgtm

#1116 controllers: kubelet: cleanup platform code
  controllers/kubeletconfig_controller.go
  main.go
Labels: approved, lgtm, cherry-pick-candidate

#1119 internal: buildinfo: add missing test coverage
  internal/api/buildinfo/types_test.go
Labels: approved

#1118 objstate: api: kickoff tests
  pkg/objectstate/api/api.go
  pkg/objectstate/api/api_test.go
Labels: approved

#1120 e2e: must-gather: fix the setup process
  test/e2e/install/install_test.go
  test/e2e/must-gather/must_gather_suite_test.go
  test/e2e/must-gather/must_gather_test.go
  test/utils/deploy/deploy.go
  test/utils/deploy/hypershift.go
  test/utils/deploy/kubernetes.go
  test/utils/deploy/openshift.go
Labels: approved, lgtm, cherry-pick-candidate

#1121 [release-4.18][manual] e2e: must-gather: fix the setup process
  test/e2e/install/install_test.go
  test/e2e/must-gather/must_gather_suite_test.go
  test/e2e/must-gather/must_gather_test.go
  test/utils/deploy/deploy.go
  test/utils/deploy/hypershift.go
  test/utils/deploy/kubernetes.go
  test/utils/deploy/openshift.go
Labels: approved

#1122 buildhelper: try harder to get version
  internal/api/buildinfo/types.go
  internal/buildinfo/buildinfo.go
  tools/buildhelper/buildhelper.go
Labels: approved, lgtm, cherry-pick-candidate

#1106 CNF-10142: Enable NROP metrics to be to scraped securely by Prometheus
  README.md
  bundle/manifests/numaresources-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/rbac.yaml
  config/rbac/kustomization.yaml
  config/rbac/service.yaml
  main.go
Labels: approved, lgtm

#1107 CNF-11234: Enable RTE metrics to be scraped securely by Prometheus
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  main.go
  pkg/metrics/manifests/manifests.go
  pkg/metrics/manifests/manifests_test.go
  pkg/metrics/manifests/monitor/monitor.go
  pkg/metrics/manifests/monitor/monitor_test.go
  pkg/metrics/manifests/yaml/service.yaml
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/rte/rte_test.go
Labels: approved, lgtm

#1073 e2e: introduce upgrade suite
  Makefile
  hack/run-test-upgrade-e2e.sh
  test/e2e/upgrade/test_suite_upgrade_test.go
  test/e2e/upgrade/upgrade_test.go
  test/utils/deploy/find.go
Labels: approved, lgtm

#1127 vendor: bump `golang.org/x/net` -> v0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: approved, lgtm
