Repository openshift-kni/numaresources-operator, pull requests merged in 2024-10, with the labels that each got.

#1033 [release-4.15] Makefile: binary-all: support build with -tags
  Makefile
Labels: approved, lgtm

#1025 CNF-14084: controller: update MachineConfig reconciliation
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  go.mod
  go.sum
  internal/api/annotations/annotations.go
  internal/objects/objects.go
  main.go
  pkg/objectstate/rte/rte.go
  pkg/objectupdate/rte/rte.go
  test/e2e/install/install_test.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/tolerations.go
  test/utils/deploy/deploy.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/detect/detect.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/manifests.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/options/options.go
  vendor/modules.txt
Labels: approved, lgtm

#1038 rte: controller: push down machineconfig deletion support into library packages
  controllers/numaresourcesoperator_controller.go
  pkg/apply/apply.go
  pkg/apply/apply_test.go
  pkg/objectstate/objectstate.go
  pkg/objectstate/objectstate_test.go
  pkg/objectstate/rte/rte.go
  test/utils/deploy/deploy.go
Labels: approved

#1039 tree: stop using `errors.Wrapf`
  controllers/kubeletconfig_controller.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesscheduler_controller.go
  go.mod
  pkg/apply/apply.go
  pkg/hash/configmap.go
Labels: approved, lgtm

#1040 api: fix v1alpha1 backward compatibility
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
Labels: approved, cherry-pick-candidate, cherry-pick-approved

#1041 [release-4.17][manual] api: fix v1alpha1 backward compatibility
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
Labels: approved, cherry-pick-candidate

#1043 e2e: review CI lanes
  hack/run-test-e2e.sh
  hack/run-test-install-e2e.sh
  test/e2e/install/install_test.go
  test/e2e/uninstall/uninstall_test.go
Labels: approved

#1018 api: add `PoolName` and `NodeGroupStatus`
  api/numaresourcesoperator/v1/helper/nodegroup/nodegroup.go
  api/numaresourcesoperator/v1/helper/nodegroup/nodegroup_test.go
  api/numaresourcesoperator/v1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/kubeletconfig_controller_test.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  internal/objects/objects.go
  internal/objects/objects_test.go
  internal/wait/numaresources.go
  pkg/status/status_test.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
  test/e2e/rte/rte_test.go
Labels: approved, lgtm

#1045 tree: reorganize nrovalidator,nrtcacheck, their imports
  Makefile
  nrovalidate/main.go
  nrovalidate/validator/kubeletconfig.go
  nrovalidate/validator/machineconfigpools.go
  nrovalidate/validator/noderesourcetopologies.go
  nrovalidate/validator/noderesourcetopologies_test.go
  nrovalidate/validator/podstatus.go
  nrovalidate/validator/schedcache.go
  nrovalidate/validator/validator.go
  nrovalidate/validator/validator_test.go
  test/e2e/serial/config/config.go
  test/e2e/tools/nrovalidate_test.go
  tools/nrtcacheck/nrtcacheck.go
Labels: approved

#1044 api: deprecate v1alpha1
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
Labels: approved, cherry-pick-candidate

#1046 Report created RTE daemonsets in operator status and fix status sync issue
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
Labels: approved, lgtm

#1049 Cleanups 20241017
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
Labels: approved

#1052 controller: use slice instead of map to conserve consistent order
  api/numaresourcesoperator/v1/namespacedname.go
  controllers/numaresourcesoperator_controller.go
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#1050 nrop: cleanup dangling objects removal
  controllers/numaresourcesoperator_controller.go
  internal/dangling/dangling.go
Labels: approved

#1013 e2e: add tests for PoolName and NodeGroupStatus
  api/numaresourcesoperator/v1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1/numaresourcesoperator_types_test.go
  internal/api/features/_topics.json
  internal/wait/daemonset.go
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#1057 Prepare for cleaning up status computation
  controllers/controllers.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesscheduler_controller.go
  pkg/status/status.go
  pkg/status/status_test.go
Labels: approved

#1028 pkg: use `errors.Join` instead of appending to slice
  controllers/numaresourcesoperator_controller.go
  internal/dangling/dangling.go
  pkg/validation/validation.go
  test/utils/padder/padder.go
  tools/verify-commit/verify-commit.go
Labels: approved, lgtm

#1055 OCPBUGS-42523: allow single MCP match per node group by default
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  internal/api/annotations/annotations.go
  internal/api/annotations/annotations_test.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
Labels: approved, lgtm
