Repository openshift-kni/numaresources-operator, pull requests merged in 2024-09, with the labels that each got.

#992 [release-4.14] add features introspection for e2e tests
  .github/workflows/e2e-tools.yml
  doc/features/README.md
  internal/api/features/_topics.json
  internal/api/features/topics.go
  internal/api/features/topics_test.go
  internal/api/features/types.go
  internal/api/features/types_test.go
  main.go
  test/e2e/serial/README.md
  test/e2e/tools/mkginkgolabelfilter_test.go
  test/e2e/tools/tools_test.go
  tools/mkginkgolabelfilter/mkginkgolabelfilter.go
Labels: approved, lgtm

#993 [release-4.13] add features introspection for e2e tests
  .github/workflows/e2e-tools.yml
  doc/features/README.md
  internal/api/features/_topics.json
  internal/api/features/topics.go
  internal/api/features/topics_test.go
  internal/api/features/types.go
  internal/api/features/types_test.go
  main.go
  test/e2e/serial/README.md
  test/e2e/tools/mkginkgolabelfilter_test.go
  test/e2e/tools/tools_test.go
  tools/mkginkgolabelfilter/mkginkgolabelfilter.go
Labels: approved, lgtm

#995 manifests: labels: don't match using new labels
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, cherry-pick-candidate

#994 tree: version: move to 4.18
  .github/workflows/release-testsuite.yaml
  Dockerfile.must-gather
  Makefile
  README.tests.md
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  config/samples/nodetopology_v1_numaresourcesscheduler.yaml
  config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml
  doc/examples/sched.debug.yaml
  doc/examples/sched.ha.yaml
  doc/examples/sched.nocache.yaml
  doc/examples/sched.yaml
  internal/api/features/types.go
  internal/api/features/types_test.go
  test/e2e/must-gather/README.md
  test/e2e/must-gather/must_gather_suite_test.go
  test/e2e/serial/README.md
  test/utils/objects/objects.go
Labels: approved, do-not-merge/hold

#1009 doc: examples: use ctrreschk releases
  doc/examples/pod.ctrreschk.yaml
  doc/examples/pod.lshwinfo.yaml
  doc/examples/pods.testgroup.yaml
Labels: approved

#1011 Makefile: bump tooling version
  Dockerfile.bundle
  Makefile
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/default/kustomization.yaml
  config/kind-ci/kustomization.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/scorecard/kustomization.yaml
  hack/verify-generated.sh
Labels: approved, lgtm

#1016 gh actions: bump more action versions
  .github/workflows/cibuild.yml
  .github/workflows/ciformat.yml
  .github/workflows/cilint-custom.yml
  .github/workflows/cilint.yml
  .github/workflows/civerify-commit.yml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yml
  .github/workflows/e2e.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/release-operator.yaml
  .github/workflows/release-testsuite.yaml
  .github/workflows/support-tools.yml
Labels: approved

#1017 gh actions: ci: unify fast lanes
  .github/workflows/ci.yml
  .github/workflows/cibuild.yml
  .github/workflows/ciformat.yml
  .github/workflows/cilint-custom.yml
  .github/workflows/cilint.yml
  .github/workflows/civerify-commit.yml
Labels: approved, lgtm

#1020 api: docs: start documenting nodegroup and tree
  api/numaresourcesoperator/v1/helper/nodegroup/nodegroup.go
Labels: approved, lgtm

#1023 deps: deploy: mco: crd: catch up with ocp/mcp/pull/4597
  hack/deploy-mco-crds.sh
Labels: approved, lgtm

#1021 gh actions: bump setup-go, fix inconsistent naming
  .github/workflows/ci.yaml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yaml
  .github/workflows/e2e.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/release-operator.yaml
  .github/workflows/release-testsuite.yaml
  .github/workflows/support-tools.yaml
  hack/kind-config-e2e-no-registry.yaml
  tools/catkubeletconfmap/catkubeletconfmap.go
Labels: approved
