Repository openshift-kni/numaresources-operator, pull requests merged in 2024-01, with the labels that each got.

#806 OCPBUGS-25763: Set base CSV replaces field
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#811 runner: enable custom execution of test suites
  Dockerfile.openshift.tests
Labels: approved, lgtm, ok-to-test

#816 hack: e2e: support hierarchical tiers in the runner
  hack/run-test-serial-e2e.sh
Labels: approved

#817 deps: deployer: consume ocp415 selinux fixes
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/assets.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.14.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.15.cil
  vendor/modules.txt
Labels: approved, lgtm

#813 tree: version: kickoff 4.16
  .github/workflows/release-testsuite.yaml
  Dockerfile.must-gather
  Makefile
  README.tests.md
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  config/samples/nodetopology_v1_numaresourcesscheduler.yaml
  config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml
  doc/examples/sched.debug.yaml
  doc/examples/sched.nocache.yaml
  doc/examples/sched.yaml
  test/e2e/must-gather/README.md
  test/e2e/must-gather/must_gather_suite_test.go
  test/utils/objects/objects.go
Labels: approved

#801 improve support to coexist with standard scheduler
  api/numaresourcesoperator/v1/numaresourcesoperator_defaults.go
  api/numaresourcesoperator/v1/numaresourcesoperator_defaults_test.go
  api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_normalize.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_normalize_test.go
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  pkg/objectupdate/rte/rte_test.go
  test/e2e/serial/tests/scheduler_cache.go
  test/utils/noderesourcetopologies/noderesourcetopologies.go
Labels: approved, lgtm

#827 runner: replaced CMD
  Dockerfile.openshift.tests
Labels: approved, lgtm, ok-to-test

#828 [release-4.14][manual] deps: bump deployer to v0.17.1
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/assets.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.14.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.15.cil
  vendor/modules.txt
Labels: approved, lgtm

#820 [release-4.14] deps: consume RTE 0.15.3
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/sysinfo/hugepages.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/sysinfo/memory.go
  vendor/modules.txt
Labels: approved

#832 serial: tests: introduce tier 0
  test/e2e/install/install_test.go
  test/e2e/serial/tests/non_regression_fundamentals.go
  test/e2e/serial/tests/scheduler_cache.go
  test/e2e/serial/tests/scheduler_cache_stall.go
  test/e2e/serial/tests/workload_placement_resources.go
  test/e2e/serial/tests/workload_placement_tmpol.go
Labels: approved, lgtm

#810 tree: clientset: remove unused and unsupported code
  hack/update-codegen.sh
  pkg/k8sclientset/config.go
  pkg/k8sclientset/generated/clientset/versioned/clientset.go
  pkg/k8sclientset/generated/clientset/versioned/doc.go
  pkg/k8sclientset/generated/clientset/versioned/fake/clientset_generated.go
  pkg/k8sclientset/generated/clientset/versioned/fake/doc.go
  pkg/k8sclientset/generated/clientset/versioned/fake/register.go
  pkg/k8sclientset/generated/clientset/versioned/scheme/doc.go
  pkg/k8sclientset/generated/clientset/versioned/scheme/register.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/doc.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/fake/doc.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/fake/fake_numaresourcesoperator.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/fake/fake_numaresourcesoperator_client.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/fake/fake_numaresourcesscheduler.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/generated_expansion.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/numaresourcesoperator.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/numaresourcesoperator_client.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1/numaresourcesscheduler.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/doc.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/fake/doc.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/fake/fake_numaresourcesoperator.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/fake/fake_numaresourcesoperator_client.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/fake/fake_numaresourcesscheduler.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/generated_expansion.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/numaresourcesoperator.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/numaresourcesoperator_client.go
  pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/numaresourcesscheduler.go
Labels: approved
