Repository openshift-kni/numaresources-operator, pull requests merged in 2025-07, with the labels that each got.

#1501 [release 4.12] konflux: Configure catalog to 4.12.15
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/.gitkeep
  .konflux/catalog/numaresources-operator/catalog.yaml
  Makefile
Labels: approved, lgtm

#1537 e2e:config: support old RTE config format
  test/internal/configuration/configuration.go
Labels: approved, lgtm

#1540 [release-4.19] konflux: update tekton tasks digests and pull latest RPMs
  .konflux/must-gather/redhat.repo
  .konflux/must-gather/rpms.in.yaml
  .konflux/must-gather/rpms.lock.yaml
  .tekton/build-pipeline-must-gather.yaml
  .tekton/numaresources-must-gather-4-19-pull-request.yaml
  .tekton/numaresources-must-gather-4-19-push.yaml
Labels: approved, lgtm, do-not-merge/hold

#1499 [release 4.14] konflux: Configure catalog to 4.14.10
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/.gitkeep
  .konflux/catalog/numaresources-operator/catalog.yaml
  Makefile
Labels: approved, lgtm

#1497 [release 4.15] konflux: Configure catalog to 4.15.8
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/.gitkeep
  .konflux/catalog/numaresources-operator/catalog.yaml
  Makefile
Labels: approved, lgtm

#1595 [release-4.19] konflux: must-gather: restore `tar` rpm
  .konflux/must-gather/rpms.lock.yaml
Labels: approved, lgtm

#1563 [release-4.17] cleanup: konflux: mustgather: remove redundant lines and restore `tar`
  .konflux/must-gather/redhat.repo
  .konflux/must-gather/rpms.lock.yaml
Labels: approved, lgtm

#1541 [release-4.18] konflux: update tekton tasks digests and pull latest RPMs
  .konflux/must-gather/redhat.repo
  .konflux/must-gather/rpms.in.yaml
  .konflux/must-gather/rpms.lock.yaml
  .tekton/build-pipeline-must-gather.yaml
  .tekton/numaresources-must-gather-4-18-pull-request.yaml
  .tekton/numaresources-must-gather-4-18-push.yaml
Labels: approved, lgtm

#1548 [release-4.15] konflux: update tekton tasks digests and pull latest RPMs
  .konflux/must-gather/redhat.repo
  .konflux/must-gather/rpms.in.yaml
  .konflux/must-gather/rpms.lock.yaml
  .tekton/build-pipeline-must-gather.yaml
  .tekton/numaresources-must-gather-4-15-pull-request.yaml
  .tekton/numaresources-must-gather-4-15-push.yaml
Labels: approved, lgtm

#1600 chore: project: move to golangci-lint v2
  .golangci.yml
  Makefile
  hack/sort-imports.py
  internal/schedcache/synced.go
Labels: approved

#1495 [release 4.17] konflux: Configure catalog to 4.17.5
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/.gitkeep
  .konflux/catalog/numaresources-operator/catalog.yaml
  Makefile
Labels: approved, lgtm

#1550 [release-4.14] konflux: update tekton tasks digests and pull latest RPMs
  .konflux/must-gather/redhat.repo
  .konflux/must-gather/rpms.in.yaml
  .konflux/must-gather/rpms.lock.yaml
  .tekton/build-pipeline-must-gather.yaml
  .tekton/numaresources-must-gather-4-14-pull-request.yaml
  .tekton/numaresources-must-gather-4-14-push.yaml
Labels: approved, lgtm

#1547 [release-4.16] konflux: update tekton tasks digests and pull latest RPMs
  .konflux/must-gather/redhat.repo
  .konflux/must-gather/rpms.in.yaml
  .konflux/must-gather/rpms.lock.yaml
  .tekton/build-pipeline-must-gather.yaml
  .tekton/numaresources-must-gather-4-16-pull-request.yaml
  .tekton/numaresources-must-gather-4-16-push.yaml
Labels: approved, lgtm

#1616 konflux: Add new IDMS configuration to use for integration tests
  .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
Labels: approved, lgtm

#1615 deps: downgrade oauth2 from 0.27 -> 0.26
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: approved, lgtm

#1605 CNF-18350: Enforce Network Policies (UPDATED)
  .konflux/bundle/metadata/annotations.yaml
  .konflux/catalog/numaresources-operator/catalog.yaml
  Dockerfile.bundle
  Makefile
  bundle/manifests/numaresources-allow-webhook-traffic_networking.k8s.io_v1_networkpolicy.yaml
  bundle/manifests/numaresources-ingress-to-operator-metrics_networking.k8s.io_v1_networkpolicy.yaml
  bundle/manifests/numaresources-operator-default-deny-all_networking.k8s.io_v1_networkpolicy.yaml
  bundle/manifests/numaresources-operator-egress-to-api-server_networking.k8s.io_v1_networkpolicy.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/default/kustomization.yaml
  config/networkpolicy/deny-all.yaml
  config/networkpolicy/egress-to-api-server.yaml
  config/networkpolicy/ingress-to-metrics.yaml
  config/networkpolicy/kustomization.yaml
  config/rbac/role.yaml
  internal/controller/numaresourcesoperator_controller.go
  pkg/metrics/manifests/monitor/monitor.go
  pkg/numaresourcesscheduler/manifests/manifests.go
  pkg/numaresourcesscheduler/manifests/manifests_test.go
  pkg/numaresourcesscheduler/manifests/sched/sched.go
  pkg/numaresourcesscheduler/manifests/yaml/networkpolicy.apiserver.yaml
  pkg/numaresourcesscheduler/manifests/yaml/networkpolicy.yaml
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
  pkg/objectstate/rte/rte.go
  test/e2e/serial/tests/network_policy.go
  test/internal/deploy/find.go
Labels: approved, lgtm

#1637 e2e: serial: change deprecated reboot labels to new reboot label
  test/e2e/serial/tests/tolerations.go
Labels: approved, lgtm

#1657 hack: verify commit: more debug logs
  hack/verify-commits.sh
Labels: approved

#1684 NO-JIRA:e2e:networkpolicy: do not mask context
  test/e2e/serial/tests/network_policy.go
Labels: approved, lgtm

#1682 konflux: catalog and image pinning alignments
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/.gitkeep
  .konflux/catalog/numaresources-operator/catalog.yaml
  Makefile
Labels: approved, lgtm

#1691 internal: api: annotations: document lifecycle
  internal/api/annotations/annotations.go
Labels: approved

#1689 review scheduler resources requests
  internal/api/annotations/annotations.go
  internal/api/annotations/annotations_test.go
  internal/controller/numaresourcesscheduler_controller.go
  internal/controller/numaresourcesscheduler_controller_test.go
  pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
  pkg/objectupdate/sched/sched.go
  pkg/objectupdate/sched/sched_test.go
Labels: approved, lgtm

#1681 CNF-17780:numaresourcesscheduler: support HA for HyperShift platform
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/numaresourcesoperator_controller.go
  internal/controller/numaresourcesscheduler_controller.go
  internal/controller/numaresourcesscheduler_controller_test.go
  pkg/objectstate/rte/rte.go
Labels: approved, lgtm

#1526 test: nrosched: clarify docstring for CheckNROSchedulerAvailable()
  test/e2e/serial/tests/scheduler_removal.go
  test/internal/nrosched/nrosched.go
Labels: approved, lgtm

#1599 [release-4.17] controller: test: verify RTE has a critical priority class
  controllers/numaresourcesoperator_controller_test.go
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/daemonset.yaml
  vendor/modules.txt
Labels: approved

#1596 [release-4.16] controller: test: verify RTE has a critical priority class
  controllers/numaresourcesoperator_controller_test.go
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/daemonset.yaml
  vendor/modules.txt
Labels: approved

#1695 [release-4.19][manual] review scheduler resources requests
  internal/api/annotations/annotations.go
  internal/api/annotations/annotations_test.go
  internal/controller/numaresourcesscheduler_controller.go
  internal/controller/numaresourcesscheduler_controller_test.go
  pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
  pkg/objectupdate/sched/sched.go
  pkg/objectupdate/sched/sched_test.go
Labels: approved, lgtm

#1715 scheduler controller: resource status cleanup
  internal/controller/numaresourcesoperator_controller.go
  internal/controller/numaresourcesscheduler_controller.go
  pkg/status/status.go
  pkg/status/status_test.go
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#1736 [release-4.18] Konflux: Catalog and fbc updates
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-18-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-18-push.yaml
Labels: approved, lgtm

#1739 [release-4.16] Konflux: Catalog and fbc updates
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-16-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-16-push.yaml
Labels: approved, lgtm

#1738 [release-4.17] Konflux: Catalog and fbc updates
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-17-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-17-push.yaml
Labels: approved, lgtm
