Repository openshift-kni/numaresources-operator, pull requests merged in 2025-01, with the labels that each got.

#1130 rte: metrics: merge manifests into existing manifests handling
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  main.go
  pkg/objectstate/rte/rte.go
Labels: approved, lgtm

#1138 NO-JIRA: govulncheck ci
  .github/workflows/govulncheck.yaml
Labels: approved, lgtm

#1139 chore: update copyright year
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go
  hack/boilerplate.go.txt
Labels: approved

#1114 objstate: rte: isolate platform-specific code
  controllers/numaresourcesoperator_controller.go
  pkg/objectstate/api/api.go
  pkg/objectstate/cfg/cfg.go
  pkg/objectstate/rte/machineconfigpool.go
  pkg/objectstate/rte/nodegroup.go
  pkg/objectstate/rte/rte.go
Labels: approved, lgtm, cherry-pick-candidate

#1143 makefile: add go files as a prerequisite
  Makefile
Labels: approved, lgtm

#1144 manifests: drop configmap support
  bundle/manifests/numaresources-manager-config_v1_configmap.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
Labels: approved

#1140 [release-4.18] Enable NROP metrics to be to scraped securely by Prometheus
  README.md
  bundle/manifests/numaresources-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/numaresources-manager-role_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/rbac.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service.yaml
  controllers/numaresourcesoperator_controller.go
  main.go
Labels: approved, lgtm

#1145 [release-4.18] nrop: controller: get rtestate from cluster just once
  controllers/numaresourcesoperator_controller.go
Labels: approved, lgtm

#1047 [release-4.17][manual] api: deprecate v1alpha1
  api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
Labels: approved, lgtm

#1147 Remove cluster role service RBAC permission leftover
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/numaresourcesoperator_controller.go
Labels: approved, lgtm

#1037 CNF-14833: E2E: metrics exposed securely
  test/e2e/serial/tests/metrics.go
Labels: approved, lgtm

#1149 controller: introduce custom matcher
  controllers/numaresourcesoperator_controller_test.go
  vendor/github.com/onsi/gomega/gcustom/make_matcher.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#1124 selinux: per-nodegroup SCC toggle
  api/numaresourcesoperator/v1/numaresourcesoperator_types.go
  api/numaresourcesoperator/v1/zz_generated.deepcopy.go
  bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
  config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesoperator_controller_test.go
  go.mod
  go.sum
  internal/api/annotations/helper/helper.go
  internal/api/features/_topics.json
  pkg/objectstate/rte/machineconfigpool.go
  pkg/objectstate/rte/nodegroup.go
  pkg/objectstate/rte/rte.go
  pkg/validation/validation.go
  test/e2e/install/install_test.go
  test/e2e/upgrade/upgrade_test.go
  test/utils/deploy/openshift.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/manifests.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/rte/rte.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/securitycontextconstraintv2.yaml
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/options/options.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-candidate

#1152 [release-4.18][manual] objstate: rte: isolate platform-specific code
  controllers/numaresourcesoperator_controller.go
  pkg/objectstate/api/api.go
  pkg/objectstate/cfg/cfg.go
  pkg/objectstate/rte/machineconfigpool.go
  pkg/objectstate/rte/nodegroup.go
  pkg/objectstate/rte/rte.go
Labels: approved, lgtm

#1154 CNF-15754: validation refinement
  controllers/numaresourcesoperator_controller.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
Labels: approved, lgtm

#1156 add missing unit tests
  internal/kloglevel/kloglevel.go
  internal/kloglevel/kloglevel_test.go
  pkg/objectnames/nodes_test.go
Labels: approved, lgtm

#1158 internal: remove workaround pkg
  internal/workarounds/interface.go
  internal/workarounds/prom.go
  internal/workarounds/prom_test.go
  test/e2e/install/install_test.go
Labels: approved, lgtm

#1103 [release-4.17] deps: bump deployer dep
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/numaresourcesoperator_controller.go
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/assets.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.17.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.18.cil
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/detect/detect.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/platform.go
  vendor/modules.txt
Labels: approved, lgtm

#1157 konflux: add a dockerfile to must gather
  .konflux/Dockerfile.must-gather
Labels: approved, lgtm

#1104 [release-4.16] deps: bump deployer dep
  go.mod
  go.sum
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/consts.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/schedparams.go
  vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/sched/render.go
  vendor/modules.txt
Labels: approved, lgtm

#1053 add namespacedname helper pkg
  api/numaresourcesoperator/v1/helper/namespacedname/namespacedname.go
  api/numaresourcesoperator/v1/helper/namespacedname/namespacedname_test.go
  api/numaresourcesoperator/v1/namespacedname.go
  controllers/numaresourcesoperator_controller.go
  internal/wait/job.go
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
  test/e2e/serial/tests/configuration.go
  test/e2e/serial/tests/scheduler_cache_stall.go
Labels: approved, lgtm

#1162 ci: numacell: fix dockerfile, add release flow
  .github/workflows/release-numacell.yml
  test/deviceplugin/cmd/numacell/Dockerfile
Labels: approved, lgtm

#1164 e2e: check all nodes have NRT object
  test/e2e/serial/config/config.go
Labels: approved, lgtm

#1167 ghaction: define E2E_NAMESPACE_NAME env
  .github/workflows/e2e-tools.yaml
Labels: approved, lgtm

#1165 serial:config: validate smt alignment is off
  test/e2e/serial/config/config.go
Labels: approved, lgtm

#1169 utils: move nodepool pkg under tests
  test/utils/deploy/hypershift.go
  test/utils/hypershift/nodepools/nodepools.go
  test/utils/hypershift/nodepools/nodepools_test.go
Labels: approved, lgtm

#1175 docs: update architecture.md
  ARCHITECTURE.md
Labels: approved

#1155 CNF-16537:Adjust serial suite for running on HyperShift platform [tier0]
  internal/controller/kubeletconfig_controller.go
  internal/hypershift/consts/consts.go
  internal/machineconfigpools/machineconfigpools.go
  internal/nodegroups/nodegroups.go
  nrovalidate/validator/kubeletconfig.go
  nrovalidate/validator/validator.go
  pkg/kubeletconfig/kubeletconfig.go
  test/e2e/serial/config/infra.go
  test/e2e/serial/tests/workload_placement_tmpol.go
  test/utils/clients/clients.go
Labels: approved, lgtm

#1168 serial:docs: add HyperShift section
  test/e2e/serial/README.md
Labels: approved, lgtm
