Repository openshift-kni/numaresources-operator, pull requests merged in 2025-09, with the labels that each got.

#1915 OCPBUGS-60848: controller: sched: detect and use cluster properties
  cmd/main.go
  internal/controller/numaresourcesscheduler_controller.go
  internal/controller/numaresourcesscheduler_controller_test.go
  internal/platforminfo/platforminfo.go
  internal/platforminfo/platforminfo_test.go
  internal/platforminfo/supportversion.go
  internal/platforminfo/supportversion_test.go
Labels: approved, lgtm

#1920 e2e: fix: changing wrong topologyManagerPolicy in defer func
  test/e2e/serial/tests/configuration.go
Labels: approved, lgtm

#1925 AI: docs: clarify docs
  README.ai.md
Labels: approved, lgtm

#1796 AA: go: bump to 1.24
  .devcontainer/devcontainer.json
  .github/workflows/ci.yaml
  .github/workflows/e2e-local.yaml
  .github/workflows/e2e-tools.yaml
  .github/workflows/e2e.yaml
  .github/workflows/govulncheck.yaml
  .github/workflows/release-operator.yaml
  .github/workflows/support-tools.yaml
  .konflux/Dockerfile.catalog
  .konflux/operator/konflux.Dockerfile
  Dockerfile
  Dockerfile.pause
  Dockerfile.tests
  Dockerfile.tools
  test/deviceplugin/cmd/numacell/Dockerfile
Labels: approved, lgtm

#1932 OCPBUGS-61355: [release-4.19] controller: sched: conditionally enable Shared informer by default
  api/v1/numaresourcesscheduler_types.go
  cmd/main.go
  internal/controller/numaresourcesscheduler_controller.go
  internal/controller/numaresourcesscheduler_controller_test.go
  internal/platforminfo/platforminfo.go
  internal/platforminfo/platforminfo_test.go
  internal/platforminfo/supportversion.go
  internal/platforminfo/supportversion_test.go
  pkg/status/status.go
  pkg/status/status_test.go
Labels: approved, lgtm

#1898 Update OWNERS configuration
  .konflux/OWNERS
  .tekton/OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm

#1979 OCPBUGS-61409: [release-4.18]: controller: sched: conditionally enable Shared informer by default
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  internal/platforminfo/platforminfo.go
  internal/platforminfo/platforminfo_test.go
  internal/platforminfo/supportversion.go
  internal/platforminfo/supportversion_test.go
  main.go
  pkg/status/status.go
  pkg/status/status_test.go
  test/e2e/sched/install/install_test.go
Labels: approved, lgtm

#2008 [release-4.19] sched: status: reset the status conditions to defaults
  internal/controller/numaresourcesscheduler_controller.go
  test/e2e/sched/install/install_test.go
Labels: approved, lgtm

#1378 CNF-18275: CNF-18276: e2e: serial: more cache stall tests
  test/e2e/serial/tests/non_regression_fundamentals.go
  test/e2e/serial/tests/scheduler_cache_stall.go
Labels: approved

#2068 chore(KONFLUX-6210): fix and set name and cpe label for numaresources-must-gather-4-14
  .konflux/must-gather/must-gather.konflux.Dockerfile
Labels: approved, lgtm, ok-to-test

#2009 OCPBUGS-61676: [release-4.17]: controller: sched: conditionally enable Shared informer by default
  api/numaresourcesoperator/v1/numaresourcesscheduler_types.go
  controllers/numaresourcesoperator_controller.go
  controllers/numaresourcesscheduler_controller.go
  controllers/numaresourcesscheduler_controller_test.go
  internal/platforminfo/platforminfo.go
  internal/platforminfo/platforminfo_test.go
  internal/platforminfo/supportversion.go
  internal/platforminfo/supportversion_test.go
  main.go
  pkg/status/status.go
  pkg/status/status_test.go
  test/e2e/sched/install/install_test.go
Labels: approved, lgtm

#2203 rte: consume v0.21.6 and plug debug-tools/pfpstatus
  go.mod
  go.sum
  internal/controller/numaresourcesscheduler_controller_test.go
  pkg/objectupdate/envvar/envvar.go
  pkg/objectupdate/envvar/envvar_test.go
  pkg/objectupdate/rte/rte.go
  pkg/objectupdate/rte/rte_test.go
  pkg/objectupdate/sched/sched.go
  rte/main.go
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/.gitignore
  vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go
  vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go
  vendor/github.com/openshift-kni/debug-tools/LICENSE
  vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/README.md
  vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/pfpstatus.go
  vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/pfpstatus_file.go
  vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/record/codec.go
  vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/record/recorder.go
  vendor/modules.txt
Labels: approved
