Repository openshift-kni/numaresources-operator, pull requests merged in 2025-06, with the labels that each got.

#1300 e2e: serial: rewrite tests for reliability
  internal/baseload/baseload.go
  internal/resourcelist/resourcelist.go
  internal/resourcelist/resourcelist_test.go
  internal/wait/deployment.go
  test/e2e/serial/tests/non_regression.go
  test/e2e/serial/tests/scheduler_cache.go
  test/e2e/serial/tests/scheduler_removal.go
  test/e2e/serial/tests/workload_overhead.go
  test/e2e/serial/tests/workload_placement.go
  test/e2e/serial/tests/workload_unschedulable.go
  test/internal/fixture/fixture.go
  test/internal/noderesourcetopologies/nrts.go
  test/internal/nrosched/nrosched.go
Labels: approved

#1285 CNF-17778: CNF-17779: schedulercontroller: High availability by default
  api/v1/numaresourcesscheduler_defaults.go
  api/v1/numaresourcesscheduler_defaults_test.go
  api/v1/numaresourcesscheduler_normalize_test.go
  cmd/main.go
  internal/controller/numaresourcesscheduler_controller.go
  internal/controller/numaresourcesscheduler_controller_test.go
  test/e2e/sched/install/install_test.go
Labels: approved, lgtm

#1376 Konflux alignments for labeling and prefetching
  .konflux/README.md
  .konflux/bundle/bundle.konflux.Dockerfile
  .konflux/container-build.args
  .konflux/operator/konflux.Dockerfile
  .konflux/operator/redhat.repo
  .tekton/build-pipeline.yaml
  .tekton/numaresources-operator-4-20-pull-request.yaml
  .tekton/numaresources-operator-4-20-push.yaml
  .tekton/numaresources-operator-bundle-4-20-push.yaml
Labels: approved, lgtm

#1377 Konflux: update renovate configuration
  renovate.json
Labels: approved, lgtm

#1367 [release-4.16] Backport Konflux changes to 4.16
  .konflux/OWNERS
  .konflux/README.md
  .konflux/bundle/bundle.konflux.Dockerfile
  .konflux/bundle/metadata/annotations.yaml
  .konflux/bundle/overlay/map_images.in.yaml
  .konflux/bundle/overlay/overlay.bash
  .konflux/bundle/overlay/pin_images.in.yaml
  .konflux/bundle/tests/scorecard/config.yaml
  .konflux/container-build.args
  .konflux/operator/konflux.Dockerfile
  .konflux/operator/redhat.repo
  .konflux/operator/rpms.in.yaml
  .konflux/operator/rpms.lock.yaml
  .tekton/OWNERS
  .tekton/build-pipeline.yaml
  .tekton/numaresources-operator-4-16-pull-request.yaml
  .tekton/numaresources-operator-4-16-push.yaml
  .tekton/numaresources-operator-bundle-4-16-pull-request.yaml
  .tekton/numaresources-operator-bundle-4-16-push.yaml
  OWNERS_ALIASES
Labels: approved, lgtm

#1366 [release-4.17] Backport Konflux changes to 4.17
  .konflux/OWNERS
  .konflux/README.md
  .konflux/bundle/bundle.konflux.Dockerfile
  .konflux/bundle/metadata/annotations.yaml
  .konflux/bundle/overlay/map_images.in.yaml
  .konflux/bundle/overlay/overlay.bash
  .konflux/bundle/overlay/pin_images.in.yaml
  .konflux/bundle/tests/scorecard/config.yaml
  .konflux/container-build.args
  .konflux/operator/konflux.Dockerfile
  .konflux/operator/redhat.repo
  .konflux/operator/rpms.in.yaml
  .konflux/operator/rpms.lock.yaml
  .tekton/OWNERS
  .tekton/build-pipeline.yaml
  .tekton/numaresources-operator-4-17-pull-request.yaml
  .tekton/numaresources-operator-4-17-push.yaml
  .tekton/numaresources-operator-bundle-4-17-pull-request.yaml
  .tekton/numaresources-operator-bundle-4-17-push.yaml
  OWNERS_ALIASES
Labels: approved, lgtm

#1369 [release-4.14] Backport Konflux changes to 4.14
  .konflux/OWNERS
  .konflux/README.md
  .konflux/bundle/bundle.konflux.Dockerfile
  .konflux/bundle/metadata/annotations.yaml
  .konflux/bundle/overlay/map_images.in.yaml
  .konflux/bundle/overlay/overlay.bash
  .konflux/bundle/overlay/pin_images.in.yaml
  .konflux/bundle/tests/scorecard/config.yaml
  .konflux/container-build.args
  .konflux/operator/konflux.Dockerfile
  .konflux/operator/redhat.repo
  .konflux/operator/rpms.in.yaml
  .konflux/operator/rpms.lock.yaml
  .tekton/OWNERS
  .tekton/build-pipeline.yaml
  .tekton/numaresources-operator-4-14-pull-request.yaml
  .tekton/numaresources-operator-4-14-push.yaml
  .tekton/numaresources-operator-bundle-4-14-pull-request.yaml
  .tekton/numaresources-operator-bundle-4-14-push.yaml
  OWNERS_ALIASES
Labels: approved, lgtm

#1331 [release 4.18] Backport Konflux changes to 4.18
  .konflux/OWNERS
  .konflux/README.md
  .konflux/bundle/bundle.konflux.Dockerfile
  .konflux/bundle/metadata/annotations.yaml
  .konflux/bundle/overlay/map_images.in.yaml
  .konflux/bundle/overlay/overlay.bash
  .konflux/bundle/overlay/pin_images.in.yaml
  .konflux/bundle/tests/scorecard/config.yaml
  .konflux/container-build.args
  .konflux/operator/konflux.Dockerfile
  .konflux/operator/redhat.repo
  .konflux/operator/rpms.in.yaml
  .konflux/operator/rpms.lock.yaml
  .tekton/OWNERS
  .tekton/build-pipeline.yaml
  .tekton/numaresources-operator-4-18-pull-request.yaml
  .tekton/numaresources-operator-4-18-push.yaml
  .tekton/numaresources-operator-bundle-4-18-pull-request.yaml
  .tekton/numaresources-operator-bundle-4-18-push.yaml
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test

#1314 [release-4.19] Backport Konflux changes to 4.19
  .konflux/OWNERS
  .konflux/README.md
  .konflux/bundle/bundle.konflux.Dockerfile
  .konflux/bundle/metadata/annotations.yaml
  .konflux/bundle/overlay/map_images.in.yaml
  .konflux/bundle/overlay/overlay.bash
  .konflux/bundle/overlay/pin_images.in.yaml
  .konflux/bundle/tests/scorecard/config.yaml
  .konflux/container-build.args
  .konflux/operator/konflux.Dockerfile
  .konflux/operator/redhat.repo
  .konflux/operator/rpms.in.yaml
  .konflux/operator/rpms.lock.yaml
  .tekton/OWNERS
  .tekton/build-pipeline.yaml
  .tekton/numaresources-operator-4-19-pull-request.yaml
  .tekton/numaresources-operator-4-19-push.yaml
  .tekton/numaresources-operator-bundle-4-19-pull-request.yaml
  .tekton/numaresources-operator-bundle-4-19-push.yaml
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test

#1334 [release-4.16]: Onboard numaresources must-gather to konflux
  .konflux/must-gather/must-gather.konflux.Dockerfile
  .konflux/must-gather/rpms.in.yaml
  .konflux/must-gather/rpms.lock.yaml
  .tekton/numaresources-must-gather-4-16-pull-request.yaml
  .tekton/numaresources-must-gather-4-16-push.yaml
Labels: approved, lgtm

#1335 [release-4.15]: Onboard numaresources must-gather to konflux
  .konflux/must-gather/must-gather.konflux.Dockerfile
  .konflux/must-gather/rpms.in.yaml
  .konflux/must-gather/rpms.lock.yaml
  .tekton/numaresources-must-gather-4-15-pull-request.yaml
  .tekton/numaresources-must-gather-4-15-push.yaml
Labels: approved, lgtm

#1452 [release-4.12]: Konflux: Catalog configuration for 4.12
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/catalog.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-12-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-12-push.yaml
  Makefile
  hack/konflux-update-catalog-template.sh
  hack/konflux-update-task-refs.sh
  hack/konflux-validate-related-images-production.sh
Labels: approved, lgtm

#1444 [release-4.14]: Konflux: Catalog configuration for 4.14
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/catalog.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-14-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-14-push.yaml
  Makefile
  hack/konflux-update-catalog-template.sh
  hack/konflux-update-task-refs.sh
  hack/konflux-validate-related-images-production.sh
Labels: approved, lgtm

#1445 [release-4.13]: Konflux: Catalog configuration for 4.13
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/catalog.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-13-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-13-push.yaml
  Makefile
  hack/konflux-update-catalog-template.sh
  hack/konflux-update-task-refs.sh
  hack/konflux-validate-related-images-production.sh
Labels: approved, lgtm

#1443 [release-4.15]: Konflux: Catalog configuration for 4.15
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/catalog.yaml
  .tekton/build-pipeline.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-15-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-15-push.yaml
  Makefile
  hack/konflux-update-catalog-template.sh
  hack/konflux-update-task-refs.sh
  hack/konflux-validate-related-images-production.sh
Labels: approved, lgtm

#1442 [release-4.16]: Konflux: Catalog configuration for 4.16
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/catalog.yaml
  .tekton/build-pipeline.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-16-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-16-push.yaml
  Makefile
  hack/konflux-update-catalog-template.sh
  hack/konflux-update-task-refs.sh
  hack/konflux-validate-related-images-production.sh
Labels: approved, lgtm

#1456 [release-4.13] konflux catalog fixes
  .konflux/catalog/numaresources-operator/catalog.yaml
  .tekton/build-pipeline.yaml
  .tekton/fbc-pipeline.yaml
  Makefile
Labels: approved, lgtm, ok-to-test

#1462 [release 4.16] konflux: fix catalog bundle format
  .konflux/catalog/numaresources-operator/catalog.yaml
  Makefile
Labels: approved, lgtm

#1457 [release-4.14] konflux catalog fixes
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/numaresources-operator/catalog.yaml
  .tekton/build-pipeline.yaml
  .tekton/fbc-pipeline.yaml
  Makefile
Labels: approved, lgtm

#1447 [release-4.18] tools: pass on bots commits
  tools/verify-commit/verify-commit.go
Labels: approved, lgtm

#1449 operator: fix and clean commandline
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  cmd/main.go
  config/manager/manager.yaml
Labels: approved

#1448 rbac: controller: sched: add permission to watch nodes
  bundle/manifests/numaresources-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/numaresourcesscheduler_controller.go
Labels: approved

#1313 controller: minimize update calls (reduced)
  pkg/numaresourcesscheduler/objectstate/sched/sched.go
  pkg/objectstate/api/api.go
  pkg/objectstate/merge/merge.go
Labels: approved, lgtm

#1458 [release-4.20]: Konflux: Catalog configuration for 4.20
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/numaresources-operator/catalog.yaml
  .tekton/build-pipeline.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/numaresources-operator-fbc-4-20-pull-request.yaml
  .tekton/numaresources-operator-fbc-4-20-push.yaml
  Makefile
  hack/konflux-update-catalog-template.sh
  hack/konflux-update-task-refs.sh
  hack/konflux-validate-related-images-production.sh
Labels: approved, lgtm, ok-to-test

#1477 [release-4.19] Konflux: prepare catalog for z streams
  .konflux/bundle/overlay/overlay.bash
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/numaresources-operator/.gitkeep
  .konflux/catalog/numaresources-operator/catalog.yaml
  Makefile
Labels: approved, lgtm

#1491 [release 4.12]: konflux: fix catalog 4.12 versions
  .konflux/Dockerfile.catalog
  .konflux/catalog/catalog-template.in.yaml
Labels: approved, lgtm

#1493 [release 4.19] konflux: z stream update 4.19.1
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
Labels: approved, lgtm, ok-to-test

#1504 Revert "Merge pull request #1493 from yanirq/konflux_4_19_1"
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
Labels: approved, lgtm

#1506 [release 4.18] konflux: set 4.18 bundle to image digest
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
Labels: approved, lgtm

#1518 [release-4.19]: Konflux: fix must gather rpm fetching
  .konflux/must-gather/rpms.lock.yaml
  .tekton/numaresources-must-gather-4-19-pull-request.yaml
  .tekton/numaresources-must-gather-4-19-push.yaml
Labels: approved, lgtm

#1525 [release-4.14]: Konflux: fix must gather rpm fetching
  .konflux/must-gather/rpms.lock.yaml
  .tekton/numaresources-must-gather-4-14-pull-request.yaml
  .tekton/numaresources-must-gather-4-14-push.yaml
Labels: approved, lgtm

#1524 [release-4.15]: Konflux: fix must gather rpm fetching
  .konflux/must-gather/rpms.lock.yaml
  .tekton/numaresources-must-gather-4-15-pull-request.yaml
  .tekton/numaresources-must-gather-4-15-push.yaml
Labels: approved, lgtm

#1522 [release-4.17]: Konflux: fix must gather rpm fetching
  .konflux/must-gather/rpms.lock.yaml
  .tekton/numaresources-must-gather-4-17-pull-request.yaml
  .tekton/numaresources-must-gather-4-17-push.yaml
Labels: approved, lgtm

#1536 hack: add a script to reformat the imports
  Makefile
  hack/sort-imports.py
Labels: approved, lgtm
